# -*- coding: UTF-8 -*-
# split feature file: simple_triggers - module
from header_common import *
from header_operations import *
from header_parties import *
from header_items import *
from header_skills import *
from header_triggers import *
from header_troops import *
from header_music import *
from header_terrain_types import *
from module_factions import dplmc_factions_end
from module_constants import *

simple_triggers_dk_invasion_lco = [
  ##diplomacy end
  

## Tocan+ ## Invasion
# ne dk
   
## Invasion check
  (1,
    [
      (eq,"$invaded",0),
      (ge,"$setting_invasion_time",1),
      (store_current_hours,":time"),
      (ge,":time","$setting_invasion_time"),
      (assign,"$invaded",1),
#      (display_message,"@A mysterious foreign power has descended upon the land.",0xff4040),
#      (play_sound,"snd_quest_cancelled"),
      (assign, "$g_dplmc_terrain_advantage", DPLMC_TERRAIN_ADVANTAGE_DISABLE),
	  (faction_set_slot, "fac_dark_knights", slot_faction_state, sfs_active), ##Tocan Invasion
      (call_script, "script_change_troop_faction", "trp_dark_knight_lord", "fac_dark_knights"),
      (call_script, "script_change_troop_faction", "trp_dark_knight_lord1", "fac_dark_knights"),
      (call_script, "script_change_troop_faction", "trp_dark_knight_lord2", "fac_dark_knights"),
      (call_script, "script_change_troop_faction", "trp_dark_knight_lord3", "fac_dark_knights"),
      (call_script, "script_change_troop_faction", "trp_dark_knight_lord4", "fac_dark_knights"),
      (call_script, "script_change_troop_faction", "trp_dark_knight_lord5", "fac_dark_knights"),
      (call_script, "script_change_troop_faction", "trp_dark_knight_lord6", "fac_dark_knights"),
      (call_script, "script_change_troop_faction", "trp_dark_knight_lord7", "fac_dark_knights"),
      (call_script, "script_change_troop_faction", "trp_dark_knight_lord8", "fac_dark_knights"),
      (call_script, "script_change_troop_faction", "trp_dark_knight_lord9", "fac_dark_knights"),
      (call_script, "script_change_troop_faction", "trp_dark_knight_lord10", "fac_dark_knights"),
      (call_script, "script_change_troop_faction", "trp_dark_knight_lord11", "fac_dark_knights"),
      (call_script, "script_change_troop_faction", "trp_dark_knight_lord12", "fac_dark_knights"),
      (call_script, "script_change_troop_faction", "trp_dark_knight_lord13", "fac_dark_knights"),
      (call_script, "script_change_troop_faction", "trp_dark_knight_lord14", "fac_dark_knights"),
      (call_script, "script_change_troop_faction", "trp_dark_knight_lord15", "fac_dark_knights"),
      (call_script, "script_change_troop_faction", "trp_dark_knight_lord16", "fac_dark_knights"),
      (call_script, "script_change_troop_faction", "trp_dark_knight_lord17", "fac_dark_knights"),
      (call_script, "script_change_troop_faction", "trp_dark_knight_lord18", "fac_dark_knights"),
      (call_script, "script_change_troop_faction", "trp_dark_knight_lord19", "fac_dark_knights"),
      (call_script, "script_change_troop_faction", "trp_dark_knight_lord20", "fac_dark_knights"),
	  
	  
	  (try_begin),
	       # player is head of own faction
	       (eq, "$players_kingdom", "fac_player_supporters_faction"),
		   (set_relation, "fac_player_supporters_faction", "fac_dark_knights", -40),
		   # select random other faction
		   # (store_random_in_range,":rand",0,1),
		   # (try_for_range, ":faction_no", kingdoms_begin, kingdoms_end),
		   # (neq, ":faction_found", 1),
           # (faction_slot_eq, ":faction_no", slot_faction_state, sfs_active),
           # (neq, ":faction_no", "fac_player_supporters_faction"),
		   # (neq, ":faction_no", "fac_dark_knights"),
		   
		   # (store_random_in_range,":rand",0,1),
		   # (eq,":rand",0),
		    # (set_relation, ":faction_no", "fac_dark_knights", -40),
			# (assign, ":center_no", "p_town_5"),
			# (str_store_faction_name,s1,":faction_no"),
			# (str_store_faction_name,s3,"fac_player_supporters_faction"),
			# (assign, ":faction_found", 1), 
		   # (try_end), 
		   
		   # (try_begin), 
		   # (neq, ":faction_found", 1), 
           # (store_random_in_range,":rand",0,1),
		    # (try_for_range, ":faction_no", kingdoms_begin, kingdoms_end),
			# (neq, ":faction_found", 1),
            # (faction_slot_eq, ":faction_no", slot_faction_state, sfs_active),
            # (neq, ":faction_no", "fac_player_supporters_faction"),
		    # (neq, ":faction_no", "fac_dark_knights"),
		    # (store_random_in_range,":rand",0,1),
		    # (eq,":rand",0),
		    # (set_relation, ":faction_no", "fac_dark_knights", -40),
			# (assign, ":center_no", "p_town_5"),
			# (assign, ":faction_found", 1), 
			# (str_store_faction_name,s1,":faction_no"),
			# (str_store_faction_name,s3,"fac_player_supporters_faction"),
		    # (try_end), 	
           #(try_end),		   
		   
		   
	 (store_random_in_range,":rand",0,11),
      (try_begin),
        (eq,":rand",0),
        (assign, ":center_no", "p_town_3"),
        (set_relation, "fac_kingdom_1", "fac_dark_knights", -40),
        (str_store_faction_name,s1,"fac_kingdom_1"),
      (try_end),
	  (str_store_faction_name,s3,"fac_player_supporters_faction"),
	  
	  (else_try),   
           # player is unattached
           (neg|is_between, "$players_kingdom", kingdoms_begin, kingdoms_end),
      (store_random_in_range,":rand",0,11),
      (try_begin),
        (eq,":rand",0),
        (assign, ":center_no", "p_town_3"),
        (set_relation, "fac_kingdom_4", "fac_dark_knights", -40),
        (set_relation, "fac_kingdom_2", "fac_dark_knights", -40),
        (set_relation, "fac_kingdom_12", "fac_dark_knights", -40),
        (str_store_faction_name,s1,"fac_kingdom_6"),
        (str_store_faction_name,s3,"fac_kingdom_2"),
        (str_store_faction_name,s4,"fac_kingdom_12"),
      (else_try),
        (eq,":rand",1),
        (assign, ":center_no", "p_town_3"),
        (set_relation, "fac_kingdom_6", "fac_dark_knights", -40),
        (set_relation, "fac_kingdom_7", "fac_dark_knights", -40),
        (set_relation, "fac_kingdom_8", "fac_dark_knights", -40),
        (str_store_faction_name,s1,"fac_kingdom_6"),
        (str_store_faction_name,s3,"fac_kingdom_7"),
        (str_store_faction_name,s4,"fac_kingdom_8"),
      (else_try),
        (eq,":rand",2),
        (assign, ":center_no", "p_town_3"),
        (set_relation, "fac_kingdom_6", "fac_dark_knights", -40),
        (set_relation, "fac_kingdom_7", "fac_dark_knights", -40),
        (set_relation, "fac_kingdom_8", "fac_dark_knights", -40),
        (str_store_faction_name,s1,"fac_kingdom_6"),
        (str_store_faction_name,s3,"fac_kingdom_7"),
        (str_store_faction_name,s4,"fac_kingdom_8"),
      (else_try),
	    (eq,":rand",3),
        (assign, ":center_no", "p_town_3"),
        (set_relation, "fac_kingdom_6", "fac_dark_knights", -40),
        (set_relation, "fac_kingdom_3", "fac_dark_knights", -40),
        (str_store_faction_name,s1,"fac_kingdom_6"),
        (str_store_faction_name,s3,"fac_kingdom_3"),
      (else_try), 
	    (eq,":rand",4),
        (assign, ":center_no", "p_town_3"),
        (set_relation, "fac_kingdom_1", "fac_dark_knights", -40),
        (set_relation, "fac_kingdom_5", "fac_dark_knights", -40),
        (set_relation, "fac_kingdom_6", "fac_dark_knights", -40),
        (str_store_faction_name,s1,"fac_kingdom_5"),
        (str_store_faction_name,s3,"fac_kingdom_6"),
        (str_store_faction_name,s4,"fac_kingdom_1"),
      (else_try), 
	    (eq,":rand",5),
        (assign, ":center_no", "p_town_3"),
        (set_relation, "fac_kingdom_3", "fac_dark_knights", -40),
        (set_relation, "fac_kingdom_6", "fac_dark_knights", -40),
        (set_relation, "fac_kingdom_8", "fac_dark_knights", -40),
        (str_store_faction_name,s1,"fac_kingdom_3"),
        (str_store_faction_name,s3,"fac_kingdom_6"),
        (str_store_faction_name,s4,"fac_kingdom_8"),
      (else_try), 
	    (eq,":rand",6),
        (assign, ":center_no", "p_town_3"),
        (set_relation, "fac_kingdom_3", "fac_dark_knights", -40),
        (set_relation, "fac_kingdom_6", "fac_dark_knights", -40),
        (set_relation, "fac_kingdom_8", "fac_dark_knights", -40),
        (str_store_faction_name,s1,"fac_kingdom_3"),
        (str_store_faction_name,s3,"fac_kingdom_6"),
        (str_store_faction_name,s4,"fac_kingdom_8"),
      (else_try), 
        (assign, ":center_no", "p_town_3"),
        (set_relation, "fac_kingdom_6", "fac_dark_knights", -40),
        (set_relation, "fac_kingdom_5", "fac_dark_knights", -40),
        (str_store_faction_name,s1,"fac_kingdom_6"),
        (str_store_faction_name,s3,"fac_kingdom_5"),
      (try_end),
		   
		   
	  (else_try),   
	       # player is a vassal
	       (set_relation, "$players_kingdom", "fac_dark_knights", -40),
		   # want them also to attack nearby kingdom
		   (store_random_in_range,":rand",0,1),
		   (try_begin), 
		    (eq, "$players_kingdom", "fac_kingdom_1"),
		     (try_begin), 
		     (eq,":rand",0),
			   (try_begin), 
		       (faction_slot_eq, "fac_kingdom_2",  slot_faction_state, sfs_active),
			   (set_relation, "fac_kingdom_2", "fac_dark_knights", -40),
			   	  (assign, ":center_no", "p_town_8"),
	              (str_store_faction_name,s1,"fac_kingdom_2"),
				  (str_store_faction_name,s3,"$players_kingdom"),

			   (else_try), 
		       (faction_slot_eq, "fac_kingdom_7",  slot_faction_state, sfs_active),
			   (set_relation, "fac_kingdom_7", "fac_dark_knights", -40),		
	           (assign, ":center_no", "p_town_15"),
	           (str_store_faction_name,s1,"fac_kingdom_7"),		
               (str_store_faction_name,s3,"$players_kingdom"),			   
			   (try_end),
		     (else_try), 
			   (try_begin), 
		       (faction_slot_eq, "fac_kingdom_7",  slot_faction_state, sfs_active),
			   (set_relation, "fac_kingdom_7", "fac_dark_knights", -40),
			   	  (assign, ":center_no", "p_town_15"),
	              (str_store_faction_name,s1,"fac_kingdom_4"),
				  (str_store_faction_name,s3,"$players_kingdom"),
			   (else_try), 
		       (faction_slot_eq, "fac_kingdom_2",  slot_faction_state, sfs_active),
			   (set_relation, "fac_kingdom_2", "fac_dark_knights", -40),	
	             (assign, ":center_no", "p_town_8"),
	             (str_store_faction_name,s1,"fac_kingdom_2"),	
                 (str_store_faction_name,s3,"$players_kingdom"),				 
			   (try_end),
			 (try_end),
			 
			(else_try), 
		    (eq, "$players_kingdom", "fac_kingdom_2"),
		     (try_begin), 
		     (eq,":rand",0),
			   (try_begin), 
		       (faction_slot_eq, "fac_kingdom_1",  slot_faction_state, sfs_active),
			   (set_relation, "fac_kingdom_1", "fac_dark_knights", -40),
			   	  (assign, ":center_no", "p_town_6"),
	              (str_store_faction_name,s1,"fac_kingdom_1"),
				                   (str_store_faction_name,s3,"$players_kingdom"),	
			   (else_try), 
		       (faction_slot_eq, "fac_kingdom_4",  slot_faction_state, sfs_active),
			   (set_relation, "fac_kingdom_4", "fac_dark_knights", -40),	
	           (assign, ":center_no", "p_town_5"),
	           (str_store_faction_name,s1,"fac_kingdom_4"),	
                 (str_store_faction_name,s3,"$players_kingdom"),				   
			   (try_end),
		     (else_try), 
			   (try_begin), 
		       (faction_slot_eq, "fac_kingdom_4",  slot_faction_state, sfs_active),
			   (set_relation, "fac_kingdom_4", "fac_dark_knights", -40),
			   	  (assign, ":center_no", "p_town_5"),
	              (str_store_faction_name,s1,"fac_kingdom_4"),
				                   (str_store_faction_name,s3,"$players_kingdom"),	
			   (else_try), 
		       (faction_slot_eq, "fac_kingdom_1",  slot_faction_state, sfs_active),
			   (set_relation, "fac_kingdom_1", "fac_dark_knights", -40),	
			   	  (assign, ":center_no", "p_town_6"),
	              (str_store_faction_name,s1,"fac_kingdom_1"),		
                 (str_store_faction_name,s3,"$players_kingdom"),					  
			   (try_end),
			 (try_end),	

			(else_try), 
		    (eq, "$players_kingdom", "fac_kingdom_3"),
		     (try_begin), 
		     (eq,":rand",0),
			   (try_begin), 
		       (faction_slot_eq, "fac_kingdom_9",  slot_faction_state, sfs_active),
			   (set_relation, "fac_kingdom_9", "fac_dark_knights", -40),
			   	  (assign, ":center_no", "p_town_18"),
	              (str_store_faction_name,s1,"fac_kingdom_9"),
				                   (str_store_faction_name,s3,"$players_kingdom"),	
			   (else_try), 
		       (faction_slot_eq, "fac_kingdom_8",  slot_faction_state, sfs_active),
			   (set_relation, "fac_kingdom_8", "fac_dark_knights", -40),	
	           (assign, ":center_no", "p_town_2"),
	           (str_store_faction_name,s1,"fac_kingdom_8"),			
                 (str_store_faction_name,s3,"$players_kingdom"),				   
			   (try_end),
		     (else_try), 
			   (try_begin), 
		       (faction_slot_eq, "fac_kingdom_8",  slot_faction_state, sfs_active),
			   (set_relation, "fac_kingdom_8", "fac_dark_knights", -40),
			   	  (assign, ":center_no", "p_town_2"),
	              (str_store_faction_name,s1,"fac_kingdom_8"),   
				                   (str_store_faction_name,s3,"$players_kingdom"),	
			   (else_try), 
		       (faction_slot_eq, "fac_kingdom_9",  slot_faction_state, sfs_active),
			   (set_relation, "fac_kingdom_9", "fac_dark_knights", -40),		
	           (assign, ":center_no", "p_town_18"),
	           (str_store_faction_name,s1,"fac_kingdom_9"),			    
			   (str_store_faction_name,s3,"$players_kingdom"),	
			   (try_end),
			 (try_end),			

			(else_try), 
		    (eq, "$players_kingdom", "fac_kingdom_4"),
		     (try_begin), 
		     (eq,":rand",0),
			   (try_begin), 
		       (faction_slot_eq, "fac_kingdom_2",  slot_faction_state, sfs_active),
			   (set_relation, "fac_kingdom_2", "fac_dark_knights", -40),
	           (assign, ":center_no", "p_town_8"),
	           (str_store_faction_name,s1,"fac_kingdom_2"),		
			     (str_store_faction_name,s3,"$players_kingdom"),	
			   (else_try), 
		       (faction_slot_eq, "fac_kingdom_7",  slot_faction_state, sfs_active),
			   (set_relation, "fac_kingdom_7", "fac_dark_knights", -40),		
			   	  (assign, ":center_no", "p_town_15"),
	              (str_store_faction_name,s1,"fac_kingdom_7"),		
                 (str_store_faction_name,s3,"$players_kingdom"),					  
			   (try_end),
		     (else_try), 
			   (try_begin), 
		       (faction_slot_eq, "fac_kingdom_7",  slot_faction_state, sfs_active),
			   (set_relation, "fac_kingdom_7", "fac_dark_knights", -40),
			   	  (assign, ":center_no", "p_town_15"),
	              (str_store_faction_name,s1,"fac_kingdom_7"),
				    (str_store_faction_name,s3,"$players_kingdom"),	
			   (else_try), 
		       (faction_slot_eq, "fac_kingdom_2",  slot_faction_state, sfs_active),
			   (set_relation, "fac_kingdom_2", "fac_dark_knights", -40),	
	           (assign, ":center_no", "p_town_8"),
	           (str_store_faction_name,s1,"fac_kingdom_2"),		
               (str_store_faction_name,s3,"$players_kingdom"),				   
			   (try_end),
			 (try_end),		

			(else_try), 
		    (eq, "$players_kingdom", "fac_kingdom_5"),
		     (try_begin), 
		     (eq,":rand",0),
			   (try_begin), 
		       (faction_slot_eq, "fac_kingdom_1",  slot_faction_state, sfs_active),
			   (set_relation, "fac_kingdom_1", "fac_dark_knights", -40),
			   	  (assign, ":center_no", "p_town_6"),
	              (str_store_faction_name,s1,"fac_kingdom_1"),		
                  (str_store_faction_name,s3,"$players_kingdom"),					  
			   (else_try), 
		       (faction_slot_eq, "fac_kingdom_6",  slot_faction_state, sfs_active),
			   (set_relation, "fac_kingdom_6", "fac_dark_knights", -40),		
	            (assign, ":center_no", "p_town_19"),
	            (str_store_faction_name,s1,"fac_kingdom_6"),		
                (str_store_faction_name,s3,"$players_kingdom"),					
			   (try_end),
		     (else_try), 
			   (try_begin), 
		       (faction_slot_eq, "fac_kingdom_6",  slot_faction_state, sfs_active),
			   (set_relation, "fac_kingdom_6", "fac_dark_knights", -40),
			   	  (assign, ":center_no", "p_town_19"),
	              (str_store_faction_name,s1,"fac_kingdom_6"),
				    (str_store_faction_name,s3,"$players_kingdom"),	
			   (else_try), 
		       (faction_slot_eq, "fac_kingdom_1",  slot_faction_state, sfs_active),
			   (set_relation, "fac_kingdom_1", "fac_dark_knights", -40),	
			   	  (assign, ":center_no", "p_town_6"),
	              (str_store_faction_name,s1,"fac_kingdom_1"),	
                  (str_store_faction_name,s3,"$players_kingdom"),					  
			   (try_end),
			 (try_end),			
			 
			(else_try), 
		    (eq, "$players_kingdom", "fac_kingdom_6"),
		     (try_begin), 
		     (eq,":rand",0),
			   (try_begin), 
		       (faction_slot_eq, "fac_kingdom_5",  slot_faction_state, sfs_active),
			   (set_relation, "fac_kingdom_5", "fac_dark_knights", -40),
			   	  (assign, ":center_no", "p_town_22"),
	              (str_store_faction_name,s1,"fac_kingdom_5"),
				    (str_store_faction_name,s3,"$players_kingdom"),	
			   (else_try), 
		       (faction_slot_eq, "fac_kingdom_1",  slot_faction_state, sfs_active),
			   (set_relation, "fac_kingdom_1", "fac_dark_knights", -40),	
	              (assign, ":center_no", "p_town_6"),
	              (str_store_faction_name,s1,"fac_kingdom_1"),			
                  (str_store_faction_name,s3,"$players_kingdom"),					  
			   (try_end),
		     (else_try), 
			   (try_begin), 
		       (faction_slot_eq, "fac_kingdom_1",  slot_faction_state, sfs_active),
			   (set_relation, "fac_kingdom_1", "fac_dark_knights", -40),
			   	  (assign, ":center_no", "p_town_6"),
	              (str_store_faction_name,s1,"fac_kingdom_1"),
				    (str_store_faction_name,s3,"$players_kingdom"),	
			   (else_try), 
		       (faction_slot_eq, "fac_kingdom_5",  slot_faction_state, sfs_active),
			   (set_relation, "fac_kingdom_5", "fac_dark_knights", -40),		
	            (assign, ":center_no", "p_town_22"),
	            (str_store_faction_name,s1,"fac_kingdom_5"),	
                (str_store_faction_name,s3,"$players_kingdom"),					
			   (try_end),
			 (try_end),			
			 
			(else_try), 
		    (eq, "$players_kingdom", "fac_kingdom_5"),
		     (try_begin), 
		     (eq,":rand",0),
			   (try_begin), 
		       (faction_slot_eq, "fac_kingdom_1",  slot_faction_state, sfs_active),
			   (set_relation, "fac_kingdom_1", "fac_dark_knights", -40),
			   	  (assign, ":center_no", "p_town_6"),
	              (str_store_faction_name,s1,"fac_kingdom_1"),		
                  (str_store_faction_name,s3,"$players_kingdom"),					  
			   (else_try), 
		       (faction_slot_eq, "fac_kingdom_6",  slot_faction_state, sfs_active),
			   (set_relation, "fac_kingdom_6", "fac_dark_knights", -40),		
	            (assign, ":center_no", "p_town_19"),
	            (str_store_faction_name,s1,"fac_kingdom_6"),		
                (str_store_faction_name,s3,"$players_kingdom"),					
			   (try_end),
		     (else_try), 
			   (try_begin), 
		       (faction_slot_eq, "fac_kingdom_6",  slot_faction_state, sfs_active),
			   (set_relation, "fac_kingdom_6", "fac_dark_knights", -40),
			   	  (assign, ":center_no", "p_town_19"),
	              (str_store_faction_name,s1,"fac_kingdom_6"),
				    (str_store_faction_name,s3,"$players_kingdom"),	
			   (else_try), 
		       (faction_slot_eq, "fac_kingdom_1",  slot_faction_state, sfs_active),
			   (set_relation, "fac_kingdom_1", "fac_dark_knights", -40),	
			   	  (assign, ":center_no", "p_town_6"),
	              (str_store_faction_name,s1,"fac_kingdom_1"),	
                  (str_store_faction_name,s3,"$players_kingdom"),					  
			   (try_end),
			 (try_end),			
			 
			(else_try), 
		    (eq, "$players_kingdom", "fac_kingdom_7"),
		     (try_begin), 
		     (eq,":rand",0),
			   (try_begin), 
		       (faction_slot_eq, "fac_kingdom_4",  slot_faction_state, sfs_active),
			   (set_relation, "fac_kingdom_4", "fac_dark_knights", -40),
			   	  (assign, ":center_no", "p_town_5"),
	              (str_store_faction_name,s1,"fac_kingdom_4"),
				    (str_store_faction_name,s3,"$players_kingdom"),	
			   (else_try), 
		       (faction_slot_eq, "fac_kingdom_8",  slot_faction_state, sfs_active),
			   (set_relation, "fac_kingdom_8", "fac_dark_knights", -40),	
	              (assign, ":center_no", "p_town_2"),
	              (str_store_faction_name,s1,"fac_kingdom_8"),			
                  (str_store_faction_name,s3,"$players_kingdom"),					  
			   (try_end),
		     (else_try), 
			   (try_begin), 
		       (faction_slot_eq, "fac_kingdom_8",  slot_faction_state, sfs_active),
			   (set_relation, "fac_kingdom_8", "fac_dark_knights", -40),
			   	  (assign, ":center_no", "p_town_2"),
	              (str_store_faction_name,s1,"fac_kingdom_8"),
				    (str_store_faction_name,s3,"$players_kingdom"),	
			   (else_try), 
		       (faction_slot_eq, "fac_kingdom_4",  slot_faction_state, sfs_active),
			   (set_relation, "fac_kingdom_4", "fac_dark_knights", -40),		
	            (assign, ":center_no", "p_town_5"),
	            (str_store_faction_name,s1,"fac_kingdom_4"),	
                (str_store_faction_name,s3,"$players_kingdom"),					
			   (try_end),
			 (try_end),		
			 
			(else_try), 
		    (eq, "$players_kingdom", "fac_kingdom_8"),
		     (try_begin), 
		     (eq,":rand",0),
			   (try_begin), 
		       (faction_slot_eq, "fac_kingdom_1",  slot_faction_state, sfs_active),
			   (set_relation, "fac_kingdom_1", "fac_dark_knights", -40),
			   	  (assign, ":center_no", "p_town_6"),
	              (str_store_faction_name,s1,"fac_kingdom_1"),
				    (str_store_faction_name,s3,"$players_kingdom"),	
			   (else_try), 
		       (faction_slot_eq, "fac_kingdom_3",  slot_faction_state, sfs_active),
			   (set_relation, "fac_kingdom_3", "fac_dark_knights", -40),	
	              (assign, ":center_no", "p_town_10"),
	              (str_store_faction_name,s1,"fac_kingdom_3"),			
                  (str_store_faction_name,s3,"$players_kingdom"),					  
			   (try_end),
		     (else_try), 
			   (try_begin), 
		       (faction_slot_eq, "fac_kingdom_3",  slot_faction_state, sfs_active),
			   (set_relation, "fac_kingdom_3", "fac_dark_knights", -40),
			   	  (assign, ":center_no", "p_town_10"),
	              (str_store_faction_name,s1,"fac_kingdom_3"),
				    (str_store_faction_name,s3,"$players_kingdom"),	
			   (else_try), 
		       (faction_slot_eq, "fac_kingdom_1",  slot_faction_state, sfs_active),
			   (set_relation, "fac_kingdom_1", "fac_dark_knights", -40),		
	            (assign, ":center_no", "p_town_6"),
	            (str_store_faction_name,s1,"fac_kingdom_1"),	
                (str_store_faction_name,s3,"$players_kingdom"),					
			   (try_end),
			 (try_end),		
			 
			(else_try), 
		    (eq, "$players_kingdom", "fac_kingdom_9"),
		     (try_begin), 
		     (eq,":rand",0),
			   (try_begin), 
		       (faction_slot_eq, "fac_kingdom_3",  slot_faction_state, sfs_active),
			   (set_relation, "fac_kingdom_3", "fac_dark_knights", -40),
			   	  (assign, ":center_no", "p_town_10"),
	              (str_store_faction_name,s1,"fac_kingdom_3"),
				    (str_store_faction_name,s3,"$players_kingdom"),	
			   (else_try), 
		       (faction_slot_eq, "fac_kingdom_8",  slot_faction_state, sfs_active),
			   (set_relation, "fac_kingdom_8", "fac_dark_knights", -40),	
	              (assign, ":center_no", "p_town_2"),
	              (str_store_faction_name,s1,"fac_kingdom_8"),			
                  (str_store_faction_name,s3,"$players_kingdom"),					  
			   (try_end),
		     (else_try), 
			   (try_begin), 
		       (faction_slot_eq, "fac_kingdom_8",  slot_faction_state, sfs_active),
			   (set_relation, "fac_kingdom_8", "fac_dark_knights", -40),
			   	  (assign, ":center_no", "p_town_2"),
	              (str_store_faction_name,s1,"fac_kingdom_8"),
				    (str_store_faction_name,s3,"$players_kingdom"),	
			   (else_try), 
		       (faction_slot_eq, "fac_kingdom_3",  slot_faction_state, sfs_active),
			   (set_relation, "fac_kingdom_3", "fac_dark_knights", -40),		
	            (assign, ":center_no", "p_town_10"),
	            (str_store_faction_name,s1,"fac_kingdom_3"),	
                (str_store_faction_name,s3,"$players_kingdom"),					
			   (try_end),
			 (try_end),	

			(else_try), 
		    (eq, "$players_kingdom", "fac_kingdom_10"),
		     (try_begin), 
		     (eq,":rand",0),
			   (try_begin), 
		       (faction_slot_eq, "fac_kingdom_1",  slot_faction_state, sfs_active),
			   (set_relation, "fac_kingdom_1", "fac_dark_knights", -40),
			   	  (assign, ":center_no", "p_town_6"),
	              (str_store_faction_name,s1,"fac_kingdom_1"),
				    (str_store_faction_name,s3,"$players_kingdom"),	
			   (else_try), 
		       (faction_slot_eq, "fac_kingdom_9",  slot_faction_state, sfs_active),
			   (set_relation, "fac_kingdom_9", "fac_dark_knights", -40),	
	              (assign, ":center_no", "p_town_10"),
	              (str_store_faction_name,s1,"fac_kingdom_9"),			
                  (str_store_faction_name,s3,"$players_kingdom"),					  
			   (try_end),
		     (else_try), 
			   (try_begin), 
		       (faction_slot_eq, "fac_kingdom_9",  slot_faction_state, sfs_active),
			   (set_relation, "fac_kingdom_9", "fac_dark_knights", -40),
			   	  (assign, ":center_no", "p_town_10"),
	              (str_store_faction_name,s1,"fac_kingdom_9"),
				    (str_store_faction_name,s3,"$players_kingdom"),	
			   (else_try), 
		       (faction_slot_eq, "fac_kingdom_1",  slot_faction_state, sfs_active),
			   (set_relation, "fac_kingdom_1", "fac_dark_knights", -40),		
	            (assign, ":center_no", "p_town_6"),
	            (str_store_faction_name,s1,"fac_kingdom_1"),	
                (str_store_faction_name,s3,"$players_kingdom"),					
			   (try_end),
			 (try_end),	
			 
			(else_try), 
		    (eq, "$players_kingdom", "fac_kingdom_11"),
		     (try_begin), 
		     (eq,":rand",0),
			   (try_begin), 
		       (faction_slot_eq, "fac_kingdom_12",  slot_faction_state, sfs_active),
			   (set_relation, "fac_kingdom_12", "fac_dark_knights", -40),
			   	  (assign, ":center_no", "p_town_25"),
	              (str_store_faction_name,s1,"fac_kingdom_12"),
				    (str_store_faction_name,s3,"$players_kingdom"),	
			   (else_try), 
		       (faction_slot_eq, "fac_kingdom_2",  slot_faction_state, sfs_active),
			   (set_relation, "fac_kingdom_2", "fac_dark_knights", -40),	
	              (assign, ":center_no", "p_town_8"),
	              (str_store_faction_name,s1,"fac_kingdom_2"),			
                  (str_store_faction_name,s3,"$players_kingdom"),					  
			   (try_end),
		     (else_try), 
			   (try_begin), 
		       (faction_slot_eq, "fac_kingdom_2",  slot_faction_state, sfs_active),
			   (set_relation, "fac_kingdom_2", "fac_dark_knights", -40),
			   	  (assign, ":center_no", "p_town_8"),
	              (str_store_faction_name,s1,"fac_kingdom_2"),
				    (str_store_faction_name,s3,"$players_kingdom"),	
			   (else_try), 
		       (faction_slot_eq, "fac_kingdom_12",  slot_faction_state, sfs_active),
			   (set_relation, "fac_kingdom_12", "fac_dark_knights", -40),		
	            (assign, ":center_no", "p_town_25"),
	            (str_store_faction_name,s1,"fac_kingdom_12"),	
                (str_store_faction_name,s3,"$players_kingdom"),					
			   (try_end),
			 (try_end),	
			 
			(else_try), 
		    (eq, "$players_kingdom", "fac_kingdom_12"),
		     (try_begin), 
		     (eq,":rand",0),
			   (try_begin), 
		       (faction_slot_eq, "fac_kingdom_11",  slot_faction_state, sfs_active),
			   (set_relation, "fac_kingdom_11", "fac_dark_knights", -40),
			   	  (assign, ":center_no", "p_town_24"),
	              (str_store_faction_name,s1,"fac_kingdom_11"),
				    (str_store_faction_name,s3,"$players_kingdom"),	
			   (else_try), 
		       (faction_slot_eq, "fac_kingdom_4",  slot_faction_state, sfs_active),
			   (set_relation, "fac_kingdom_4", "fac_dark_knights", -40),	
	              (assign, ":center_no", "p_town_5"),
	              (str_store_faction_name,s1,"fac_kingdom_4"),			
                  (str_store_faction_name,s3,"$players_kingdom"),					  
			   (try_end),
		     (else_try), 
			   (try_begin), 
		       (faction_slot_eq, "fac_kingdom_4",  slot_faction_state, sfs_active),
			   (set_relation, "fac_kingdom_4", "fac_dark_knights", -40),
			   	  (assign, ":center_no", "p_town_5"),
	              (str_store_faction_name,s1,"fac_kingdom_4"),
				    (str_store_faction_name,s3,"$players_kingdom"),	
			   (else_try), 
		       (faction_slot_eq, "fac_kingdom_11",  slot_faction_state, sfs_active),
			   (set_relation, "fac_kingdom_11", "fac_dark_knights", -40),		
	            (assign, ":center_no", "p_town_24"),
	            (str_store_faction_name,s1,"fac_kingdom_11"),	
                (str_store_faction_name,s3,"$players_kingdom"),					
			   (try_end),
			 (try_end),	

			 
			(else_try),
		    # player vassal of kingdoms 13-27 (gekokujo extended)
		    (is_between, "$players_kingdom", "fac_kingdom_13", "fac_kingdoms_end"),
		    (set_relation, "$players_kingdom", "fac_dark_knights", -40),
		    (call_script, "script_cf_select_random_walled_center_with_faction", "$players_kingdom", "trp_player"),
		    (assign, ":center_no", reg0),
		    (call_script, "script_cf_faction_get_random_enemy_faction", "$players_kingdom"),
		    (neq, reg0, "fac_dark_knights"),
		    (set_relation, reg0, "fac_dark_knights", -40),
		    (str_store_faction_name, s1, reg0),
		    (str_store_faction_name, s3, "$players_kingdom"),

			(try_end),
	  (try_end), 


	  
      # (store_random_in_range,":rand",0,5),
      # (try_begin),
        # (eq,":rand",0),
        # (assign, ":center_no", "p_town_4"),
        # (set_relation, "fac_kingdom_1", "fac_dark_knights", -40),
        # (set_relation, "fac_kingdom_5", "fac_dark_knights", -40),
        # (str_store_faction_name,s1,"fac_kingdom_1"),
        # (str_store_faction_name,s3,"fac_kingdom_5"),
      # (else_try),
        # (eq,":rand",1),
        # (assign, ":center_no", "p_town_10"),
        # (set_relation, "fac_kingdom_3", "fac_dark_knights", -40),
        # (set_relation, "fac_kingdom_2", "fac_dark_knights", -40),
        # (str_store_faction_name,s1,"fac_kingdom_3"),
        # (str_store_faction_name,s3,"fac_kingdom_2"),
      # (else_try),
        # (eq,":rand",2),
        # (assign, ":center_no", "p_town_5"),
        # (set_relation, "fac_kingdom_5", "fac_dark_knights", -40),
        # (set_relation, "fac_kingdom_1", "fac_dark_knights", -40),
        # (str_store_faction_name,s1,"fac_kingdom_5"),
        # (str_store_faction_name,s3,"fac_kingdom_1"),
      # (else_try),
	    # (eq,":rand",3),
        # (assign, ":center_no", "p_town_12"),
        # (set_relation, "fac_kingdom_4", "fac_dark_knights", -40),
        # (set_relation, "fac_kingdom_2", "fac_dark_knights", -40),
        # (str_store_faction_name,s1,"fac_kingdom_4"),
        # (str_store_faction_name,s3,"fac_kingdom_2"),
      # (else_try), # new for Sarranids
        # (assign, ":center_no", "p_town_21"),
        # (set_relation, "fac_kingdom_6", "fac_dark_knights", -40),
        # (set_relation, "fac_kingdom_3", "fac_dark_knights", -40),
        # (str_store_faction_name,s1,"fac_kingdom_6"),
        # (str_store_faction_name,s3,"fac_kingdom_3"),
      # (try_end),
      (str_store_faction_name,s2,"fac_dark_knights"),
      (display_log_message, "@{s2} has declared war against {s1}."),
      (display_log_message, "@{s2} has declared war against {s3}."),
      (display_log_message, "@{s2} has declared war against {s4}."),
	  
	  (troop_set_slot, "trp_dark_knight_lord", slot_troop_age, 48),	
	  (troop_set_slot, "trp_dark_knight_lord", slot_troop_wealth, 100000),		  
      (call_script, "script_create_kingdom_hero_party_dk", "trp_dark_knight_lord", ":center_no"),
	  
	  (troop_set_slot, "trp_dark_knight_lord1", slot_troop_age, 39),
	  (troop_set_slot, "trp_dark_knight_lord1", slot_troop_renown, 1000),
	  (troop_set_slot, "trp_dark_knight_lord1", slot_troop_wealth, 10000),		  	  
      (call_script, "script_create_kingdom_hero_party_dk", "trp_dark_knight_lord1", ":center_no"),
	  
	  (troop_set_slot, "trp_dark_knight_lord2", slot_troop_age, 31),
	  (troop_set_slot, "trp_dark_knight_lord2", slot_troop_renown, 1000),
	  (troop_set_slot, "trp_dark_knight_lord2", slot_troop_wealth, 10000),		  	  
      (call_script, "script_create_kingdom_hero_party_dk", "trp_dark_knight_lord2", ":center_no"),
	  
	  (troop_set_slot, "trp_dark_knight_lord3", slot_troop_age, 30),
	  (troop_set_slot, "trp_dark_knight_lord3", slot_troop_renown, 1000),
	  (troop_set_slot, "trp_dark_knight_lord3", slot_troop_wealth, 10000),		  	  
      (call_script, "script_create_kingdom_hero_party_dk", "trp_dark_knight_lord3", ":center_no"),
	  
	  (troop_set_slot, "trp_dark_knight_lord4", slot_troop_age, 43),	
	  (troop_set_slot, "trp_dark_knight_lord4", slot_troop_renown, 1000),
	  (troop_set_slot, "trp_dark_knight_lord4", slot_troop_wealth, 10000),		  	  
      (call_script, "script_create_kingdom_hero_party_dk", "trp_dark_knight_lord4", ":center_no"),	  
	  
	  (troop_set_slot, "trp_dark_knight_lord5", slot_troop_age, 45),	
	  (troop_set_slot, "trp_dark_knight_lord5", slot_troop_renown, 1000),
	  (troop_set_slot, "trp_dark_knight_lord5", slot_troop_wealth, 10000),		  	  
      (call_script, "script_create_kingdom_hero_party_dk", "trp_dark_knight_lord5", ":center_no"),	

	  (troop_set_slot, "trp_dark_knight_lord6", slot_troop_age, 27),
	  (troop_set_slot, "trp_dark_knight_lord6", slot_troop_renown, 600),
	  (troop_set_slot, "trp_dark_knight_lord6", slot_troop_wealth, 10000),		  	  
      (call_script, "script_create_kingdom_hero_party_dk", "trp_dark_knight_lord6", ":center_no"),	

	  (troop_set_slot, "trp_dark_knight_lord7", slot_troop_age, 44),
	  (troop_set_slot, "trp_dark_knight_lord7", slot_troop_renown, 900),
	  (troop_set_slot, "trp_dark_knight_lord7", slot_troop_wealth, 10000),		  	  
      (call_script, "script_create_kingdom_hero_party_dk", "trp_dark_knight_lord7", ":center_no"),	

	  (troop_set_slot, "trp_dark_knight_lord8", slot_troop_age, 40),
	  (troop_set_slot, "trp_dark_knight_lord8", slot_troop_renown, 800),
	  (troop_set_slot, "trp_dark_knight_lord8", slot_troop_wealth, 10000),		  	  
      (call_script, "script_create_kingdom_hero_party_dk", "trp_dark_knight_lord8", ":center_no"),	

	  (troop_set_slot, "trp_dark_knight_lord9", slot_troop_age, 31),
	  (troop_set_slot, "trp_dark_knight_lord9", slot_troop_renown, 600),
	  (troop_set_slot, "trp_dark_knight_lord9", slot_troop_wealth, 10000),		  
      (call_script, "script_create_kingdom_hero_party_dk", "trp_dark_knight_lord9", ":center_no"),	


	  (troop_set_slot, "trp_dark_knight_lord10", slot_troop_age, 29),
	  (troop_set_slot, "trp_dark_knight_lord10", slot_troop_renown, 600),
	  (troop_set_slot, "trp_dark_knight_lord10", slot_troop_wealth, 10000),		  
      (call_script, "script_create_kingdom_hero_party_dk", "trp_dark_knight_lord10", ":center_no"),	

	  (troop_set_slot, "trp_dark_knight_lord11", slot_troop_age, 34),
	  (troop_set_slot, "trp_dark_knight_lord11", slot_troop_renown, 700),
	  (troop_set_slot, "trp_dark_knight_lord11", slot_troop_wealth, 10000),		  
      (call_script, "script_create_kingdom_hero_party_dk", "trp_dark_knight_lord11", ":center_no"),	

	  (troop_set_slot, "trp_dark_knight_lord12", slot_troop_age, 24),
	  (troop_set_slot, "trp_dark_knight_lord12", slot_troop_renown, 500),
	  (troop_set_slot, "trp_dark_knight_lord12", slot_troop_wealth, 10000),		  
      (call_script, "script_create_kingdom_hero_party_dk", "trp_dark_knight_lord12", ":center_no"),	

	  (troop_set_slot, "trp_dark_knight_lord13", slot_troop_age, 35),
	  (troop_set_slot, "trp_dark_knight_lord13", slot_troop_renown, 700),
	  (troop_set_slot, "trp_dark_knight_lord13", slot_troop_wealth, 10000),		  
      (call_script, "script_create_kingdom_hero_party_dk", "trp_dark_knight_lord13", ":center_no"),	

	  (troop_set_slot, "trp_dark_knight_lord14", slot_troop_age, 25),
	  (troop_set_slot, "trp_dark_knight_lord14", slot_troop_renown, 500),
	  (troop_set_slot, "trp_dark_knight_lord14", slot_troop_wealth, 10000),		  
      (call_script, "script_create_kingdom_hero_party_dk", "trp_dark_knight_lord14", ":center_no"),		 

	  (troop_set_slot, "trp_dark_knight_lord15", slot_troop_age, 26),
	  (troop_set_slot, "trp_dark_knight_lord15", slot_troop_renown, 500),
	  (troop_set_slot, "trp_dark_knight_lord15", slot_troop_wealth, 10000),		  
      (call_script, "script_create_kingdom_hero_party_dk", "trp_dark_knight_lord15", ":center_no"),		

	  (troop_set_slot, "trp_dark_knight_lord16", slot_troop_age, 23),	
	  (troop_set_slot, "trp_dark_knight_lord16", slot_troop_renown, 500),
	  (troop_set_slot, "trp_dark_knight_lord16", slot_troop_wealth, 10000),		  
      (call_script, "script_create_kingdom_hero_party_dk", "trp_dark_knight_lord16", ":center_no"),		

	  (troop_set_slot, "trp_dark_knight_lord17", slot_troop_age, 22),
	  (troop_set_slot, "trp_dark_knight_lord17", slot_troop_renown, 500),
	  (troop_set_slot, "trp_dark_knight_lord17", slot_troop_wealth, 10000),		  
      (call_script, "script_create_kingdom_hero_party_dk", "trp_dark_knight_lord17", ":center_no"),		

	  (troop_set_slot, "trp_dark_knight_lord18", slot_troop_age, 42),
	  (troop_set_slot, "trp_dark_knight_lord18", slot_troop_renown, 800),
	  (troop_set_slot, "trp_dark_knight_lord18", slot_troop_wealth, 10000),		  
      (call_script, "script_create_kingdom_hero_party_dk", "trp_dark_knight_lord18", ":center_no"),		

	  (troop_set_slot, "trp_dark_knight_lord19", slot_troop_age, 27),
	  (troop_set_slot, "trp_dark_knight_lord19", slot_troop_renown, 600),
	  (troop_set_slot, "trp_dark_knight_lord19", slot_troop_wealth, 10000),		  
      (call_script, "script_create_kingdom_hero_party_dk", "trp_dark_knight_lord19", ":center_no"),		

	  (troop_set_slot, "trp_dark_knight_lord20", slot_troop_age, 44),	
	  (troop_set_slot, "trp_dark_knight_lord20", slot_troop_renown, 900),
	  (troop_set_slot, "trp_dark_knight_lord20", slot_troop_wealth, 10000),	  
      (call_script, "script_create_kingdom_hero_party_dk", "trp_dark_knight_lord20", ":center_no"),	
	  
	  # (troop_set_slot, "trp_dark_knight_lord", slot_troop_leaded_party, 1),
      # (troop_set_slot, "trp_dark_knight_lord1", slot_troop_leaded_party, 1),
      # (troop_set_slot, "trp_dark_knight_lord2", slot_troop_leaded_party, 1),
      # (troop_set_slot, "trp_dark_knight_lord3", slot_troop_leaded_party, 1),
      # (troop_set_slot, "trp_dark_knight_lord4", slot_troop_leaded_party, 1),
      # (troop_set_slot, "trp_dark_knight_lord5", slot_troop_leaded_party, 1),
      # (troop_set_slot, "trp_dark_knight_lord6", slot_troop_leaded_party, 1),
      # (troop_set_slot, "trp_dark_knight_lord7", slot_troop_leaded_party, 1),
      # (troop_set_slot, "trp_dark_knight_lord8", slot_troop_leaded_party, 1),
      # (troop_set_slot, "trp_dark_knight_lord9", slot_troop_leaded_party, 1),
      # (troop_set_slot, "trp_dark_knight_lord10", slot_troop_leaded_party, 1),
      # (troop_set_slot, "trp_dark_knight_lord11", slot_troop_leaded_party, 1),
      # (troop_set_slot, "trp_dark_knight_lord12", slot_troop_leaded_party, 1),
      # (troop_set_slot, "trp_dark_knight_lord13", slot_troop_leaded_party, 1),
      # (troop_set_slot, "trp_dark_knight_lord14", slot_troop_leaded_party, 1),
      # (troop_set_slot, "trp_dark_knight_lord15", slot_troop_leaded_party, 1),	
      # (troop_set_slot, "trp_dark_knight_lord16", slot_troop_leaded_party, 1),
      # (troop_set_slot, "trp_dark_knight_lord17", slot_troop_leaded_party, 1),
      # (troop_set_slot, "trp_dark_knight_lord18", slot_troop_leaded_party, 1),
      # (troop_set_slot, "trp_dark_knight_lord19", slot_troop_leaded_party, 1),
      # (troop_set_slot, "trp_dark_knight_lord20", slot_troop_leaded_party, 1),	  
## relations with marshall	
	  (call_script, "script_troop_change_relation_with_troop", "trp_dark_knight_lord1", "trp_dark_knight_lord", 100),
	  (call_script, "script_troop_change_relation_with_troop", "trp_dark_knight_lord1", "trp_dark_knight_lord2", 100),
	  (call_script, "script_troop_change_relation_with_troop", "trp_dark_knight_lord1", "trp_dark_knight_lord3", 100),
	  (call_script, "script_troop_change_relation_with_troop", "trp_dark_knight_lord1", "trp_dark_knight_lord4", 100),
	  (call_script, "script_troop_change_relation_with_troop", "trp_dark_knight_lord1", "trp_dark_knight_lord5", 100),
	  (call_script, "script_troop_change_relation_with_troop", "trp_dark_knight_lord1", "trp_dark_knight_lord6", 100),
	  (call_script, "script_troop_change_relation_with_troop", "trp_dark_knight_lord1", "trp_dark_knight_lord7", 100),
	  (call_script, "script_troop_change_relation_with_troop", "trp_dark_knight_lord1", "trp_dark_knight_lord8", 100),
	  (call_script, "script_troop_change_relation_with_troop", "trp_dark_knight_lord1", "trp_dark_knight_lord9", 100),
	  (call_script, "script_troop_change_relation_with_troop", "trp_dark_knight_lord1", "trp_dark_knight_lord10", 100),
	  (call_script, "script_troop_change_relation_with_troop", "trp_dark_knight_lord1", "trp_dark_knight_lord11", 100),
	  (call_script, "script_troop_change_relation_with_troop", "trp_dark_knight_lord1", "trp_dark_knight_lord12", 100),
	  (call_script, "script_troop_change_relation_with_troop", "trp_dark_knight_lord1", "trp_dark_knight_lord13", 100),
	  (call_script, "script_troop_change_relation_with_troop", "trp_dark_knight_lord1", "trp_dark_knight_lord14", 100),
	  (call_script, "script_troop_change_relation_with_troop", "trp_dark_knight_lord1", "trp_dark_knight_lord15", 100),
	  (call_script, "script_troop_change_relation_with_troop", "trp_dark_knight_lord1", "trp_dark_knight_lord16", 100),
	  (call_script, "script_troop_change_relation_with_troop", "trp_dark_knight_lord1", "trp_dark_knight_lord17", 100),
	  (call_script, "script_troop_change_relation_with_troop", "trp_dark_knight_lord1", "trp_dark_knight_lord18", 100),
	  (call_script, "script_troop_change_relation_with_troop", "trp_dark_knight_lord1", "trp_dark_knight_lord19", 100),
	  (call_script, "script_troop_change_relation_with_troop", "trp_dark_knight_lord1", "trp_dark_knight_lord20", 100),	  
## relations with king	  
	  (call_script, "script_troop_change_relation_with_troop", "trp_dark_knight_lord", "trp_dark_knight_lord1", 100),
	  (call_script, "script_troop_change_relation_with_troop", "trp_dark_knight_lord", "trp_dark_knight_lord2", 100),
	  (call_script, "script_troop_change_relation_with_troop", "trp_dark_knight_lord", "trp_dark_knight_lord3", 100),
	  (call_script, "script_troop_change_relation_with_troop", "trp_dark_knight_lord", "trp_dark_knight_lord4", 100),
	  (call_script, "script_troop_change_relation_with_troop", "trp_dark_knight_lord", "trp_dark_knight_lord5", 100),
	  (call_script, "script_troop_change_relation_with_troop", "trp_dark_knight_lord", "trp_dark_knight_lord6", 100),
	  (call_script, "script_troop_change_relation_with_troop", "trp_dark_knight_lord", "trp_dark_knight_lord7", 100),
	  (call_script, "script_troop_change_relation_with_troop", "trp_dark_knight_lord", "trp_dark_knight_lord8", 100),
	  (call_script, "script_troop_change_relation_with_troop", "trp_dark_knight_lord", "trp_dark_knight_lord9", 100),
	  (call_script, "script_troop_change_relation_with_troop", "trp_dark_knight_lord", "trp_dark_knight_lord10", 100),
	  (call_script, "script_troop_change_relation_with_troop", "trp_dark_knight_lord", "trp_dark_knight_lord11", 100),
	  (call_script, "script_troop_change_relation_with_troop", "trp_dark_knight_lord", "trp_dark_knight_lord12", 100),
	  (call_script, "script_troop_change_relation_with_troop", "trp_dark_knight_lord", "trp_dark_knight_lord13", 100),
	  (call_script, "script_troop_change_relation_with_troop", "trp_dark_knight_lord", "trp_dark_knight_lord14", 100),
	  (call_script, "script_troop_change_relation_with_troop", "trp_dark_knight_lord", "trp_dark_knight_lord15", 100),
	  (call_script, "script_troop_change_relation_with_troop", "trp_dark_knight_lord", "trp_dark_knight_lord16", 100),
	  (call_script, "script_troop_change_relation_with_troop", "trp_dark_knight_lord", "trp_dark_knight_lord17", 100),
	  (call_script, "script_troop_change_relation_with_troop", "trp_dark_knight_lord", "trp_dark_knight_lord18", 100),
	  (call_script, "script_troop_change_relation_with_troop", "trp_dark_knight_lord", "trp_dark_knight_lord19", 100),
	  (call_script, "script_troop_change_relation_with_troop", "trp_dark_knight_lord", "trp_dark_knight_lord20", 100),	  	  
	  
	  (troop_set_note_available, "trp_dark_knight_lord", 1),
	  (troop_set_note_available, "trp_dark_knight_lord1", 1),
	  (troop_set_note_available, "trp_dark_knight_lord2", 1),
	  (troop_set_note_available, "trp_dark_knight_lord3", 1),
	  (troop_set_note_available, "trp_dark_knight_lord4", 1),
	  (troop_set_note_available, "trp_dark_knight_lord5", 1),
	  (troop_set_note_available, "trp_dark_knight_lord6", 1),
	  (troop_set_note_available, "trp_dark_knight_lord7", 1),
	  (troop_set_note_available, "trp_dark_knight_lord8", 1),
	  (troop_set_note_available, "trp_dark_knight_lord9", 1),
	  (troop_set_note_available, "trp_dark_knight_lord10", 1),
	  (troop_set_note_available, "trp_dark_knight_lord11", 1),
	  (troop_set_note_available, "trp_dark_knight_lord12", 1),
	  (troop_set_note_available, "trp_dark_knight_lord13", 1),
	  (troop_set_note_available, "trp_dark_knight_lord14", 1),
	  (troop_set_note_available, "trp_dark_knight_lord15", 1),
	  (troop_set_note_available, "trp_dark_knight_lord16", 1),
	  (troop_set_note_available, "trp_dark_knight_lord17", 1),
	  (troop_set_note_available, "trp_dark_knight_lord18", 1),
	  (troop_set_note_available, "trp_dark_knight_lord19", 1),
	  (troop_set_note_available, "trp_dark_knight_lord20", 1),	  
	  
	  
	  (faction_set_note_available, "fac_dark_knights", 1), ## Tocan Invasion	
	  (call_script, "script_appoint_faction_marshall", "fac_dark_knights", "trp_dark_knight_lord1"), 	  
      (call_script, "script_update_all_notes"),	
	  
	  #right, no hanging around
	  # (call_script, "script_decide_faction_ai_dk2", "fac_dark_knights"),
	  	#xxxxxxxxxxxxxxxxxxxxxxxx
	    (faction_set_slot, "fac_dark_knights", slot_faction_ai_state, sfai_attacking_center),
        (faction_set_slot, "fac_dark_knights", slot_faction_ai_object, ":center_no"),
	
	######################### (call_script, "script_update_troop_notes", ":cur_troop"),
	
	  #(call_script, "script_find_center_to_attack_alt_dk", "trp_dark_knight_lord", 1, 0),
      # (assign, "$g_recalculate_ais", 1),
      (party_set_faction,"p_main_party","fac_player_faction"), #This is a bug fix for a bug that sometimes does and sometimes does not show up - Jinnai
      (jump_to_menu, "mnu_dk_invasion_start_warning"),
   ]),
## Are the Dark Knights a threat yet?
   (24,
    [
      (eq,"$invaded",1),
      (assign,":centers",0),
      (try_for_range,":center_no",walled_centers_begin,walled_centers_end),
        (store_faction_of_party, ":faction", ":center_no"),
        (eq,":faction","fac_dark_knights"),
        (val_add,":centers",1),
      (try_end),
      (ge,":centers",8), #4 or more walled centers, start a war with everyone
      (assign,"$invaded",2),
#      (set_relation, "fac_player_faction", "fac_dark_knights", -40),
      (try_for_range, ":faction_no", "fac_kingdom_1", "fac_kingdoms_end"),
        (set_relation, ":faction_no", "fac_dark_knights", -40),
      (try_end),
      (str_store_faction_name,s1,"fac_dark_knights"),
      (display_message,"@The leaders of Japan have realized the threat the {s1} represent and have unanimously declared war on them."),
      (assign, "$g_recalculate_ais", 1),
   ]),
## Tocan- ##


## Tocan- ##

  # #gekokujo 3.0 zaitenko's reinforcement script
  # (0.2,  #Every 0.2 game hours will the game check if there are any reinforcements in the centers.
    # [
      # (try_for_parties, ":party_no"), 
        # (party_slot_eq, ":party_no", slot_party_type, spt_reinforcement_party),  #Find parties of the type spt_reinforcement_party
        # (party_is_in_any_town, ":party_no"),  # Is the party in any town?
        # (party_get_cur_town, ":cur_center", ":party_no"), #What town are they in?
        # (call_script, "script_party_add_party_companions", ":cur_center", ":party_no"), #Add the party to the center, which is infact a party ;)
        # (party_clear, ":party_no"), #Not sure if this cleaning up is necessary, but it's a precaution so we don't have a bundle of templates lying around.
      # (try_end), 
    # ]),

  # Auto merge factions after 3 days
  (24,
   [
     (try_begin),
       (eq, "$g_faction_merge_done", 0),
       (store_current_day, ":cur_day"),
       (ge, ":cur_day", 2),
       (faction_set_slot, "fac_kingdom_28", slot_faction_state, sfs_active),
       (call_script, "script_give_center_to_faction_aux", "p_town_4", "fac_kingdom_28"),
       # if the player took over the New Government at game start, Kyoto and the throne stay with the current leader
       (faction_get_slot, ":yf_leader", "fac_kingdom_28", slot_faction_leader),
       (try_begin),
         (eq, ":yf_leader", "trp_kingdom_28_lord"),
         (call_script, "script_give_center_to_lord", "p_town_4", "trp_kingdom_28_lord", 0),
       (try_end),
       (call_script, "script_merge_factions", "fac_kingdom_28", "fac_kingdom_4", "fac_kingdom_12", "fac_kingdom_15", ":yf_leader"),
       (assign, "$g_faction_merge_done", 1),
       (jump_to_menu, "mnu_xinzhengfuchengli"),
       (play_cue_track, "track_miyasan1"),
     (try_end),
   ]),
####################################################################################################################
# LAV MODIFICATIONS START (COMPANIONS OVERSEER MOD)
    (0,
        [
            (map_free),
            (this_or_next|key_clicked, key_o),
            (neq, "$g_lco_operation", 0),
            (try_begin),
                (this_or_next|key_clicked, key_o),
                (eq, "$g_lco_operation", lco_run_presentation),
                (assign, "$g_lco_operation", 0),
                (jump_to_menu, "mnu_lco_presentation"),
            (else_try),
                (eq, "$g_lco_operation", lco_view_character),
                (assign, "$g_lco_operation", 0),
                (jump_to_menu, "mnu_lco_view_character"),
            (try_end),
        ]
    ),
# LAV MODIFICATIONS END (COMPANIONS OVERSEER MOD)
####################################################################################################################

####################################################################################################################
# TROOPS OVERVIEW MOD - P key for regular troops upgrade
    (0,
        [
            (map_free),
            (key_clicked, key_p),
            (jump_to_menu, "mnu_troops_overview"),
        ]
    ),
]
