# -*- coding: cp1254 -*-
from __future__ import absolute_import
from header_common import *
from header_presentations import *
from header_mission_templates import *
from ID_meshes import *
from header_operations import *
from header_triggers import *
from module_constants import *
from header_terrain_types import *
from module_items import *
from header_skills import *
from module_info_pages import *
from module_factions import *
from ID_postfx_params import *
from ID_factions import *
from header_parties import *

####################################################################################################################
#  New game option screen (ported from ACAN vc_options, adapted to this mod).
#  Campaign type: 0 = ROYAL SANDBOX (replace a king), 1 = SANDBOX
#  (normal character creation). Native difficulty settings included.
####################################################################################################################

presentations_game_start = [
("vc_options", 0, mesh_load_window, [
  (ti_on_presentation_load,[
    (presentation_set_duration, 999999),
    (set_fixed_point_multiplier, 1000),

    (assign, "$temp_troop", -1),
    (assign, "$g_sandbox_start_done", 0),
    (assign, "$g_sandbox_target_faction", -1),
    (call_script, "script_mcc_default_settings"),
    (assign, "$g_campaign_type", 1),

    #0. BACKGROUND
    (create_mesh_overlay, reg0, "mesh_load_window"),
    (position_set_x, pos1, 0),
    (position_set_y, pos1, 0),
    (overlay_set_position, reg0, pos1),

    #1. BUTTONS
    (create_game_button_overlay, "$g_presentation_obj_1", "@Continue"),
    (position_set_x, pos1, 825),
    (position_set_y, pos1, 25),
    (overlay_set_position, "$g_presentation_obj_1", pos1),

    (create_game_button_overlay, "$g_presentation_obj_2", "@Back"),
    (position_set_x, pos1, 625),
    (position_set_y, pos1, 25),
    (overlay_set_position, "$g_presentation_obj_2", pos1),

    #2. WELCOME MESSAGE
    (try_begin),
      (eq, reg60, 1),
      (create_text_overlay, reg1, "@Welcome to Gekokujo - Ishin no Arashi.^Before you start the game, choose a campaign type and difficulty options.", tf_center_justify|tf_with_outline),
      (overlay_set_color, reg1, 0x99CCFF),
      (position_set_x, pos1, 250),
      (position_set_y, pos1, 670),
      (overlay_set_position, reg1, pos1),
      (position_set_x, pos1, 1200),
      (position_set_y, pos1, 1200),
      (overlay_set_size, reg1, pos1),
    (try_end),

    #3. CAMPAIGN TYPE
    (create_text_overlay, reg1, "@Campaign Type:", tf_center_justify),
    (overlay_set_color, reg1, 0xAA66CC),
    (position_set_x, pos1, 1200),
    (position_set_y, pos1, 1200),
    (overlay_set_size, reg1, pos1),
    (position_set_x, pos1, 250),
    (position_set_y, pos1, 650),
    (overlay_set_position, reg1, pos1),

    (create_combo_button_overlay, "$g_presentation_obj_admin_panel_9"),
    (position_set_x, pos1, 250),
    (position_set_y, pos1, 610),
    (overlay_set_position, "$g_presentation_obj_admin_panel_9", pos1),
    (position_set_x, pos1, 800),
    (position_set_y, pos1, 800),
    (overlay_set_size, "$g_presentation_obj_admin_panel_9", pos1),
    (overlay_add_item, "$g_presentation_obj_admin_panel_9", "@ROYAL SANDBOX"),
    (overlay_add_item, "$g_presentation_obj_admin_panel_9", "@SANDBOX"),
    (try_begin),
      (eq, "$g_campaign_type", 0),
      (overlay_set_val, "$g_presentation_obj_admin_panel_9", 0),
    (else_try),
      (overlay_set_val, "$g_presentation_obj_admin_panel_9", 1),
    (try_end),

    #4. DIFFICULTY
    (create_text_overlay, reg1, "@Difficulty:", tf_center_justify),
    (overlay_set_color, reg1, 0xAA66CC),
    (position_set_x, pos1, 1200),
    (position_set_y, pos1, 1200),
    (overlay_set_size, reg1, pos1),
    (position_set_x, pos1, 250),
    (position_set_y, pos1, 570),
    (overlay_set_position, reg1, pos1),

    #5. CONTAINER
    (str_clear, s0),
    (create_text_overlay, "$g_presentation_obj_admin_panel_container", s0, tf_scrollable),
    (position_set_x, pos1, 250),
    (position_set_y, pos1, 80),
    (overlay_set_position, "$g_presentation_obj_admin_panel_container", pos1),
    (position_set_x, pos1, 350),
    (position_set_y, pos1, 460),
    (overlay_set_area_size, "$g_presentation_obj_admin_panel_container", pos1),
    (set_container_overlay, "$g_presentation_obj_admin_panel_container"),

    (position_set_x, pos1, 0),
    (position_set_y, pos1, 320),

    (create_text_overlay, reg1, "@Damage to player", 0),
    (call_script, "script_prsnt_vc_menu_helper_2"),
    (overlay_add_item, reg2, "@Reduced to 1/4 (Easiest)"),
    (overlay_add_item, reg2, "@Reduced to 1/2 (Easy)"),
    (overlay_add_item, reg2, "@Normal"),
    (options_get_damage_to_player, reg8),
    (overlay_set_val, reg2, reg8),
    (assign, "$g_presentation_obj_25", reg2),

    (create_text_overlay, reg1, "@Damage to friends", 0),
    (call_script, "script_prsnt_vc_menu_helper_2"),
    (overlay_add_item, reg2, "@Reduced to 1/2 (Easiest)"),
    (overlay_add_item, reg2, "@Reduced to 3/4 (Easy)"),
    (overlay_add_item, reg2, "@Normal"),
    (options_get_damage_to_friends, reg8),
    (overlay_set_val, reg2, reg8),
    (assign, "$g_presentation_obj_26", reg2),

    (call_script, "script_prsnt_vc_menu_helper_gap"),

    (create_text_overlay, reg1, "@Combat AI", 0),
    (call_script, "script_prsnt_vc_menu_helper_2"),
    (overlay_add_item, reg2, "@Good"),
    (overlay_add_item, reg2, "@Average"),
    (overlay_add_item, reg2, "@Poor"),
    (options_get_combat_ai, reg8),
    (overlay_set_val, reg2, reg8),
    (assign, "$g_presentation_obj_27", reg2),

    (create_text_overlay, reg1, "@Movement and combat speed", 0),
    (call_script, "script_prsnt_vc_menu_helper_2"),
    (overlay_add_item, reg2, "@Slowest"),
    (overlay_add_item, reg2, "@Slower"),
    (overlay_add_item, reg2, "@Normal"),
    (overlay_add_item, reg2, "@Faster"),
    (overlay_add_item, reg2, "@Fastest"),
    (options_get_combat_speed, reg8),
    (overlay_set_val, reg2, reg8),
    (assign, "$g_presentation_obj_29", reg2),

    (create_text_overlay, reg1, "@Campaign AI", 0),
    (call_script, "script_prsnt_vc_menu_helper_2"),
    (overlay_add_item, reg2, "@Good"),
    (overlay_add_item, reg2, "@Average"),
    (overlay_add_item, reg2, "@Poor"),
    (options_get_campaign_ai, reg8),
    (overlay_set_val, reg2, reg8),
    (assign, "$g_presentation_obj_28", reg2),

    (call_script, "script_prsnt_vc_menu_helper_gap"),

    (create_text_overlay, reg1, "@Battle size", 0),
    (call_script, "script_prsnt_vc_menu_helper_3"),
    (options_get_battle_size, reg8),
    (overlay_set_val, reg2, reg8),
    (assign, "$g_presentation_obj_30", reg2),

    (set_container_overlay, -1),

    #6. DESCRIPTION AREAS
    (str_clear, s0),
    (create_text_overlay, "$g_presentation_obj_3", s0, tf_center_justify),
    (position_set_x, pos1, 250),
    (position_set_y, pos1, 545),
    (overlay_set_position, "$g_presentation_obj_3", pos1),
    (position_set_x, pos1, 1200),
    (position_set_y, pos1, 1200),
    (overlay_set_size, "$g_presentation_obj_3", pos1),

    (str_clear, s0),
    (create_text_overlay, "$g_presentation_obj_7", s0, tf_double_space|tf_scrollable|tf_center_justify),
    (position_set_x, pos1, 625),
    (position_set_y, pos1, 80),
    (overlay_set_position, "$g_presentation_obj_7", pos1),
    (position_set_x, pos1, 320),
    (position_set_y, pos1, 300),
    (overlay_set_area_size, "$g_presentation_obj_7", pos1),
  ]),
  (ti_on_presentation_mouse_enter_leave,[
    (store_trigger_param_1, ":object"),
    (store_trigger_param_2, ":one_exit_zero_enter"),
    (str_clear, s2),
    (str_clear, s4),
    (try_begin),
      (eq, ":one_exit_zero_enter", 1),
    (else_try),
      (eq, ":object", "$g_presentation_obj_admin_panel_9"),
      (str_store_string, s2, "@Campaign type"),
      (str_store_string, s4, "@ROYAL SANDBOX: Start the game as a king of your chosen clan.^^SANDBOX: Create a new character and start a free adventure."),
    (else_try),
      (eq, ":object", "$g_presentation_obj_25"),
      (str_store_string, s2, "@Damage to player"),
      (str_store_string, s4, "@Set how much damage is done to your character."),
    (else_try),
      (eq, ":object", "$g_presentation_obj_26"),
      (str_store_string, s2, "@Damage to friends"),
      (str_store_string, s4, "@Set how much damage is done to your troops."),
    (else_try),
      (eq, ":object", "$g_presentation_obj_27"),
      (str_store_string, s2, "@Combat AI"),
      (str_store_string, s4, "@Set how well troops fight in battle."),
    (else_try),
      (eq, ":object", "$g_presentation_obj_28"),
      (str_store_string, s2, "@Campaign AI"),
      (str_store_string, s4, "@Set how smart the AI lords act on the world map."),
    (else_try),
      (eq, ":object", "$g_presentation_obj_29"),
      (str_store_string, s2, "@Movement and combat speed"),
      (str_store_string, s4, "@Set the running speed of troops in battle."),
    (else_try),
      (eq, ":object", "$g_presentation_obj_30"),
      (str_store_string, s2, "@Battle size"),
      (str_store_string, s4, "@Set how many troops can be present on the battlefield at the same time."),
    (try_end),
    (overlay_set_text, "$g_presentation_obj_3", s2),
    (overlay_set_text, "$g_presentation_obj_7", s4),
  ]),
  (ti_on_presentation_event_state_change,[
    (store_trigger_param_1, ":object"),
    (store_trigger_param_2, ":value"),
    (try_begin),
      (eq, ":object", "$g_presentation_obj_1"), ####### CONTINUE #######
      (try_begin),
        (eq, "$g_campaign_type", 1),
        # SANDBOX: Native default creation chain (gender -> backgrounds -> summary -> face -> town)
        (jump_to_menu, "mnu_start_game_1"),
        (presentation_set_duration, 0),
      (else_try),
        # ROYAL: pick the king to replace
        (start_presentation, "prsnt_select_kingdom"),
      (try_end),
    (else_try),
      (eq, ":object", "$g_presentation_obj_2"), ####### BACK #######
      (jump_to_menu, "mnu_start_game_0"),
      (presentation_set_duration, 0),
    (else_try),
      (eq, ":object", "$g_presentation_obj_admin_panel_9"), ####### CAMPAIGN TYPE #######
      (assign, "$g_campaign_type", ":value"),
    (else_try),
      (eq, ":object", "$g_presentation_obj_25"), ####### DAMAGE TO PLAYER #######
      (options_set_damage_to_player, ":value"),
    (else_try),
      (eq, ":object", "$g_presentation_obj_26"), ####### DAMAGE TO FRIENDS #######
      (options_set_damage_to_friends, ":value"),
    (else_try),
      (eq, ":object", "$g_presentation_obj_27"), ####### COMBAT AI #######
      (options_set_combat_ai, ":value"),
    (else_try),
      (eq, ":object", "$g_presentation_obj_28"), ####### CAMPAIGN AI #######
      (options_set_campaign_ai, ":value"),
    (else_try),
      (eq, ":object", "$g_presentation_obj_29"), ####### COMBAT SPEED #######
      (options_set_combat_speed, ":value"),
    (else_try),
      (eq, ":object", "$g_presentation_obj_30"), ####### BATTLE SIZE #######
      (options_set_battle_size, ":value"),
    (try_end),
  ]),
]),

####################################################################################################################
#  Normal sandbox mode - new game character creation screen (ported from ACAN
#  mcc_character_creation: gender, status, body build, mind, biography and stat
#  changes). Year and culture dropdowns removed (not applicable to this mod).
####################################################################################################################
("mcc_character_creation", 0, 0, [
  (ti_on_presentation_load,[
    (presentation_set_duration, 999999),
    (set_fixed_point_multiplier, 1000),

    (create_mesh_overlay, reg1, "mesh_load_window"),
    (position_set_x, pos1, 0),
    (position_set_y, pos1, 0),
    (overlay_set_position, reg1, pos1),

    ## Done button
    (create_game_button_overlay, "$g_presentation_obj_1", "@Done"),
    (position_set_x, pos1, 875),
    (position_set_y, pos1, 35),
    (overlay_set_position, "$g_presentation_obj_1", pos1),

    ## Back button
    (create_game_button_overlay, "$g_presentation_obj_2", "@Back"),
    (position_set_x, pos1, 700),
    (position_set_y, pos1, 35),
    (overlay_set_position, "$g_presentation_obj_2", pos1),

    ## Default button
    (create_game_button_overlay, "$g_presentation_obj_3", "@Default"),
    (position_set_x, pos1, 125),
    (position_set_y, pos1, 35),
    (overlay_set_position, "$g_presentation_obj_3", pos1),

    ## title
    (create_text_overlay, reg1, "@Character Creation", tf_center_justify),
    (position_set_x, pos1, 1500),
    (position_set_y, pos1, 1500),
    (overlay_set_size, reg1, pos1),
    (position_set_x, pos1, 500),
    (position_set_y, pos1, 690),
    (overlay_set_position, reg1, pos1),

    (assign, ":cur_y", 660+35),
    ## background
    (create_text_overlay, reg1, "@Background:", tf_center_justify),
    (position_set_x, pos1, 1200),
    (position_set_y, pos1, 1200),
    (overlay_set_size, reg1, pos1),
    (position_set_x, pos1, 150),
    (position_set_y, pos1, ":cur_y"),
    (overlay_set_position, reg1, pos1),
    (val_sub, ":cur_y", 40),

    (create_text_overlay, reg1, "@Gender:", tf_center_justify),
    (position_set_x, pos1, 1000),
    (position_set_y, pos1, 1000),
    (overlay_set_size, reg1, pos1),
    (position_set_x, pos1, 150),
    (position_set_y, pos1, ":cur_y"),
    (overlay_set_position, reg1, pos1),
    (val_sub, ":cur_y", 30),

    (create_combo_button_overlay, "$g_presentation_obj_gender"),
    (position_set_x, pos1, 175),
    (position_set_y, pos1, ":cur_y"),
    (overlay_set_position, "$g_presentation_obj_gender", pos1),
    (position_set_x, pos1, 800),
    (position_set_y, pos1, 800),
    (overlay_set_size, "$g_presentation_obj_gender", pos1),
    (overlay_add_item, "$g_presentation_obj_gender", "@Man"),
    (overlay_add_item, "$g_presentation_obj_gender", "@Woman"),
    (overlay_set_val, "$g_presentation_obj_gender", "$character_gender"),
    (val_sub, ":cur_y", 40),

    (create_text_overlay, reg1, "@Status:", tf_center_justify),
    (position_set_x, pos1, 1000),
    (position_set_y, pos1, 1000),
    (overlay_set_size, reg1, pos1),
    (position_set_x, pos1, 150),
    (position_set_y, pos1, ":cur_y"),
    (overlay_set_position, reg1, pos1),
    (val_sub, ":cur_y", 30),

    (create_combo_button_overlay, "$g_presentation_obj_father"),
    (position_set_x, pos1, 175),
    (position_set_y, pos1, ":cur_y"),
    (overlay_set_position, "$g_presentation_obj_father", pos1),
    (position_set_x, pos1, 800),
    (position_set_y, pos1, 800),
    (overlay_set_size, "$g_presentation_obj_father", pos1),
    (overlay_add_item, "$g_presentation_obj_father", "@Slave"),
    (overlay_add_item, "$g_presentation_obj_father", "@Freeman"),
    (overlay_add_item, "$g_presentation_obj_father", "@Lesser Noble"),
    (overlay_set_val, "$g_presentation_obj_father", "$background_type"),
    (val_sub, ":cur_y", 40),

    (create_text_overlay, reg1, "@Body Build:", tf_center_justify),
    (position_set_x, pos1, 1000),
    (position_set_y, pos1, 1000),
    (overlay_set_size, reg1, pos1),
    (position_set_x, pos1, 150),
    (position_set_y, pos1, ":cur_y"),
    (overlay_set_position, reg1, pos1),
    (val_sub, ":cur_y", 30),

    (create_combo_button_overlay, "$g_presentation_obj_early"),
    (position_set_x, pos1, 175),
    (position_set_y, pos1, ":cur_y"),
    (overlay_set_position, "$g_presentation_obj_early", pos1),
    (position_set_x, pos1, 800),
    (position_set_y, pos1, 800),
    (overlay_set_size, "$g_presentation_obj_early", pos1),
    (overlay_add_item, "$g_presentation_obj_early", "@Strong"),
    (overlay_add_item, "$g_presentation_obj_early", "@Agile"),
    (overlay_add_item, "$g_presentation_obj_early", "@Weak"),
    (overlay_set_val, "$g_presentation_obj_early", "$background_answer_2"),
    (val_sub, ":cur_y", 40),

    (create_text_overlay, reg1, "@Mind:", tf_center_justify),
    (position_set_x, pos1, 1000),
    (position_set_y, pos1, 1000),
    (overlay_set_size, reg1, pos1),
    (position_set_x, pos1, 150),
    (position_set_y, pos1, ":cur_y"),
    (overlay_set_position, reg1, pos1),
    (val_sub, ":cur_y", 30),

    (create_combo_button_overlay, "$g_presentation_obj_adult"),
    (position_set_x, pos1, 175),
    (position_set_y, pos1, ":cur_y"),
    (overlay_set_position, "$g_presentation_obj_adult", pos1),
    (position_set_x, pos1, 800),
    (position_set_y, pos1, 800),
    (overlay_set_size, "$g_presentation_obj_adult", pos1),
    (overlay_add_item, "$g_presentation_obj_adult", "@Genius"),
    (overlay_add_item, "$g_presentation_obj_adult", "@Shrewd"),
    (overlay_add_item, "$g_presentation_obj_adult", "@Normal"),
    (overlay_add_item, "$g_presentation_obj_adult", "@Dull"),
    (overlay_set_val, "$g_presentation_obj_adult", "$background_answer_3"),
    (val_sub, ":cur_y", 40),

    ## biography
    (create_text_overlay, reg1, "@Biography:", tf_center_justify),
    (position_set_x, pos1, 1200),
    (position_set_y, pos1, 1200),
    (overlay_set_size, reg1, pos1),
    (position_set_x, pos1, 500),
    (position_set_y, pos1, 660),
    (overlay_set_position, reg1, pos1),

    (call_script, "script_mcc_get_character_background_text"),
    (create_text_overlay, "$g_presentation_obj_story", "@{s1}", tf_double_space|tf_scrollable),
    (position_set_x, pos1, 320),
    (position_set_y, pos1, 90),
    (overlay_set_position, "$g_presentation_obj_story", pos1),
    (position_set_x, pos1, 340),
    (position_set_y, pos1, 520),
    (overlay_set_area_size, "$g_presentation_obj_story", pos1),

    ## stat changes
    (create_text_overlay, reg1, "@Stat Changes:", tf_center_justify),
    (position_set_x, pos1, 1200),
    (position_set_y, pos1, 1200),
    (overlay_set_size, reg1, pos1),
    (position_set_x, pos1, 835),
    (position_set_y, pos1, 660),
    (overlay_set_position, reg1, pos1),

    ### STRENGTH ###
    (create_text_overlay, reg1, "@Str", tf_center_justify),
    (position_set_x, pos1, 900),
    (position_set_y, pos1, 900),
    (overlay_set_size, reg1, pos1),
    (position_set_x, pos1, 760),
    (position_set_y, pos1, 620),
    (overlay_set_position, reg1, pos1),
    (create_text_overlay, "$g_presentation_obj_strength", "@0", tf_center_justify),
    (position_set_x, pos1, 850),
    (position_set_y, pos1, 850),
    (overlay_set_size, "$g_presentation_obj_strength", pos1),
    (position_set_x, pos1, 760),
    (position_set_y, pos1, 595),
    (overlay_set_position, "$g_presentation_obj_strength", pos1),

    ### AGILITY ###
    (create_text_overlay, reg1, "@Agi", tf_center_justify),
    (position_set_x, pos1, 900),
    (position_set_y, pos1, 900),
    (overlay_set_size, reg1, pos1),
    (position_set_x, pos1, 805),
    (position_set_y, pos1, 620),
    (overlay_set_position, reg1, pos1),
    (create_text_overlay, "$g_presentation_obj_agility", "@0", tf_center_justify),
    (position_set_x, pos1, 850),
    (position_set_y, pos1, 850),
    (overlay_set_size, "$g_presentation_obj_agility", pos1),
    (position_set_x, pos1, 805),
    (position_set_y, pos1, 595),
    (overlay_set_position, "$g_presentation_obj_agility", pos1),

    ### INTELLIGENCE ###
    (create_text_overlay, reg1, "@Int", tf_center_justify),
    (position_set_x, pos1, 900),
    (position_set_y, pos1, 900),
    (overlay_set_size, reg1, pos1),
    (position_set_x, pos1, 850),
    (position_set_y, pos1, 620),
    (overlay_set_position, reg1, pos1),
    (create_text_overlay, "$g_presentation_obj_intel", "@0", tf_center_justify),
    (position_set_x, pos1, 850),
    (position_set_y, pos1, 850),
    (overlay_set_size, "$g_presentation_obj_intel", pos1),
    (position_set_x, pos1, 850),
    (position_set_y, pos1, 595),
    (overlay_set_position, "$g_presentation_obj_intel", pos1),

    ### CHARISMA ###
    (create_text_overlay, reg1, "@Cha", tf_center_justify),
    (position_set_x, pos1, 900),
    (position_set_y, pos1, 900),
    (overlay_set_size, reg1, pos1),
    (position_set_x, pos1, 895),
    (position_set_y, pos1, 620),
    (overlay_set_position, reg1, pos1),
    (create_text_overlay, "$g_presentation_obj_charisma", "@0", tf_center_justify),
    (position_set_x, pos1, 850),
    (position_set_y, pos1, 850),
    (overlay_set_size, "$g_presentation_obj_charisma", pos1),
    (position_set_x, pos1, 895),
    (position_set_y, pos1, 595),
    (overlay_set_position, "$g_presentation_obj_charisma", pos1),

    ### GOLD ###
    (create_text_overlay, reg1, "@Gold"),
    (position_set_x, pos1, 900),
    (position_set_y, pos1, 900),
    (overlay_set_size, reg1, pos1),
    (position_set_x, pos1, 695),
    (position_set_y, pos1, 520),
    (overlay_set_position, reg1, pos1),
    (create_text_overlay, "$g_presentation_obj_gold", "@0", tf_center_justify),
    (position_set_x, pos1, 850),
    (position_set_y, pos1, 850),
    (overlay_set_size, "$g_presentation_obj_gold", pos1),
    (position_set_x, pos1, 805),
    (position_set_y, pos1, 520),
    (overlay_set_position, "$g_presentation_obj_gold", pos1),

    ### RENOWN ###
    (create_text_overlay, reg1, "@Renown"),
    (position_set_x, pos1, 900),
    (position_set_y, pos1, 900),
    (overlay_set_size, reg1, pos1),
    (position_set_x, pos1, 695),
    (position_set_y, pos1, 500),
    (overlay_set_position, reg1, pos1),
    (create_text_overlay, "$g_presentation_obj_renown", "@0", tf_center_justify),
    (position_set_x, pos1, 850),
    (position_set_y, pos1, 850),
    (overlay_set_size, "$g_presentation_obj_renown", pos1),
    (position_set_x, pos1, 805),
    (position_set_y, pos1, 500),
    (overlay_set_position, "$g_presentation_obj_renown", pos1),

    ### WEAPON PROF - ONE HAND ###
    (create_text_overlay, reg1, "@One Handed"),
    (position_set_x, pos1, 900),
    (position_set_y, pos1, 900),
    (overlay_set_size, reg1, pos1),
    (position_set_x, pos1, 695),
    (position_set_y, pos1, 480),
    (overlay_set_position, reg1, pos1),
    (create_text_overlay, "$g_presentation_obj_onehand", "@0", tf_center_justify),
    (position_set_x, pos1, 850),
    (position_set_y, pos1, 850),
    (overlay_set_size, "$g_presentation_obj_onehand", pos1),
    (position_set_x, pos1, 805),
    (position_set_y, pos1, 480),
    (overlay_set_position, "$g_presentation_obj_onehand", pos1),

    ### WEAPON PROF - TWO HAND ###
    (create_text_overlay, reg1, "@Two Handed"),
    (position_set_x, pos1, 900),
    (position_set_y, pos1, 900),
    (overlay_set_size, reg1, pos1),
    (position_set_x, pos1, 695),
    (position_set_y, pos1, 460),
    (overlay_set_position, reg1, pos1),
    (create_text_overlay, "$g_presentation_obj_twohand", "@0", tf_center_justify),
    (position_set_x, pos1, 850),
    (position_set_y, pos1, 850),
    (overlay_set_size, "$g_presentation_obj_twohand", pos1),
    (position_set_x, pos1, 805),
    (position_set_y, pos1, 460),
    (overlay_set_position, "$g_presentation_obj_twohand", pos1),

    ### WEAPON PROF - POLEARMS ###
    (create_text_overlay, reg1, "@Polearms"),
    (position_set_x, pos1, 900),
    (position_set_y, pos1, 900),
    (overlay_set_size, reg1, pos1),
    (position_set_x, pos1, 695),
    (position_set_y, pos1, 440),
    (overlay_set_position, reg1, pos1),
    (create_text_overlay, "$g_presentation_obj_polearm", "@0", tf_center_justify),
    (position_set_x, pos1, 850),
    (position_set_y, pos1, 850),
    (overlay_set_size, "$g_presentation_obj_polearm", pos1),
    (position_set_x, pos1, 805),
    (position_set_y, pos1, 440),
    (overlay_set_position, "$g_presentation_obj_polearm", pos1),

    ### WEAPON PROF - ARCHERY ###
    (create_text_overlay, reg1, "@Bows"),
    (position_set_x, pos1, 900),
    (position_set_y, pos1, 900),
    (overlay_set_size, reg1, pos1),
    (position_set_x, pos1, 695),
    (position_set_y, pos1, 420),
    (overlay_set_position, reg1, pos1),
    (create_text_overlay, "$g_presentation_obj_bow", "@0", tf_center_justify),
    (position_set_x, pos1, 850),
    (position_set_y, pos1, 850),
    (overlay_set_size, "$g_presentation_obj_bow", pos1),
    (position_set_x, pos1, 805),
    (position_set_y, pos1, 420),
    (overlay_set_position, "$g_presentation_obj_bow", pos1),

    ### WEAPON PROF - CROSSBOW ###
    (create_text_overlay, reg1, "@Crossbows"),
    (position_set_x, pos1, 900),
    (position_set_y, pos1, 900),
    (overlay_set_size, reg1, pos1),
    (position_set_x, pos1, 695),
    (position_set_y, pos1, 400),
    (overlay_set_position, reg1, pos1),
    (create_text_overlay, "$g_presentation_obj_xbow", "@0", tf_center_justify),
    (position_set_x, pos1, 850),
    (position_set_y, pos1, 850),
    (overlay_set_size, "$g_presentation_obj_xbow", pos1),
    (position_set_x, pos1, 805),
    (position_set_y, pos1, 400),
    (overlay_set_position, "$g_presentation_obj_xbow", pos1),

    ### WEAPON PROF - THROWING ###
    (create_text_overlay, reg1, "@Throwing"),
    (position_set_x, pos1, 900),
    (position_set_y, pos1, 900),
    (overlay_set_size, reg1, pos1),
    (position_set_x, pos1, 695),
    (position_set_y, pos1, 380),
    (overlay_set_position, reg1, pos1),
    (create_text_overlay, "$g_presentation_obj_throw", "@0", tf_center_justify),
    (position_set_x, pos1, 850),
    (position_set_y, pos1, 850),
    (overlay_set_size, "$g_presentation_obj_throw", pos1),
    (position_set_x, pos1, 805),
    (position_set_y, pos1, 380),
    (overlay_set_position, "$g_presentation_obj_throw", pos1),

    (call_script, "script_mcc_generate_skill_set", 0),
  ]),
  (ti_on_presentation_event_state_change,[
    (store_trigger_param_1, ":object"),
    (store_trigger_param_2, ":value"),
    (try_begin),
    ####### DONE BUTTON #######
      (eq, ":object", "$g_presentation_obj_1"),
      (call_script, "script_mcc_end_presentation_begin_game"),
      (assign, "$g_sandbox_start_done", 2), # SANDBOX only: town choice next
      (display_message, "@Press C on the world map to spend your attribute/skill/weapon points. Click your portrait there to edit your face.", 0x99CCFF),
      (presentation_set_duration, 0),
    (else_try), ####### BACK BUTTON #######
      (eq, ":object", "$g_presentation_obj_2"),
      (jump_to_menu, "mnu_start_game_0"),
      (presentation_set_duration, 0),
    (else_try), ####### DEFAULT BUTTON #######
      (eq, ":object", "$g_presentation_obj_3"),
      (call_script, "script_mcc_default_settings"),
      (start_presentation, "prsnt_mcc_character_creation"),
    (else_try), ####### GENDER MENU #######
      (eq, ":object", "$g_presentation_obj_gender"),
      (neq, ":value", "$character_gender"), # guard: set_val on load would otherwise reload endlessly
      (assign, "$character_gender", ":value"),
      (start_presentation, "prsnt_mcc_character_creation"),
    (else_try), ####### STATUS MENU #######
      (eq, ":object", "$g_presentation_obj_father"),
      (neq, ":value", "$background_type"),
      (assign, "$background_type", ":value"),
      (start_presentation, "prsnt_mcc_character_creation"),
    (else_try), ####### BODY BUILD MENU #######
      (eq, ":object", "$g_presentation_obj_early"),
      (neq, ":value", "$background_answer_2"),
      (assign, "$background_answer_2", ":value"),
      (start_presentation, "prsnt_mcc_character_creation"),
    (else_try), ####### MIND MENU #######
      (eq, ":object", "$g_presentation_obj_adult"),
      (neq, ":value", "$background_answer_3"),
      (assign, "$background_answer_3", ":value"),
      (start_presentation, "prsnt_mcc_character_creation"),
    (try_end),
  ]),
]),

####################################################################################################################
#  Advanced (Lordly) and Top-tier (Royal) sandbox campaign screen (ported from
#  ACAN select_kingdom). Choose the ruler to fully replace: portrait grid with
#  names, selection info on the left. Year dropdown and roman special cases removed.
####################################################################################################################
("select_kingdom", 0, mesh_load_window, [
  (ti_on_presentation_load,[
    (presentation_set_duration, 999999),
    (set_fixed_point_multiplier, 1000),

    (try_for_range, ":slot", 1, 30),
      (troop_set_slot, "trp_temp_array_a", ":slot", -1),
      (troop_set_slot, "trp_temp_array_b", ":slot", -1),
    (try_end),
    #init variables: list every kingdom that has a valid leader
    (assign, ":num_lords", 0),
    (try_for_range, ":kingdom", npc_kingdoms_begin, npc_kingdoms_end),
      (neq, ":kingdom", "fac_dark_knights"), # Tocan invasion faction: no fiefs/vassals, permanently hostile, not playable
      (faction_get_slot, ":leader", ":kingdom", slot_faction_leader),
      (try_begin),
        (is_between, ":leader", kings_begin, kingdom_ladies_end),
        (store_sub, ":slot", ":kingdom", npc_kingdoms_begin),
        (val_add, ":slot", 1),
        (troop_set_slot, "trp_temp_array_a", ":slot", ":kingdom"),
        (val_add, ":num_lords", 1),
      (try_end),
    (try_end),

    (try_begin),
      (gt, "$temp_troop", -1),
      (store_troop_faction, ":npc_faction", "$temp_troop"),

      (str_store_troop_name, s0, "$temp_troop"),
      (create_text_overlay, reg1, "@Selected: {s0}", 0),
      (position_set_x, pos1, 25),
      (position_set_y, pos1, 715),
      (overlay_set_position, reg1, pos1),
      (position_set_x, pos1, 950),
      (position_set_y, pos1, 950),
      (overlay_set_size, reg1, pos1),

      (create_mesh_overlay_with_tableau_material, reg0, -1, "tableau_troop_note_mesh", "$temp_troop"),
      (position_set_x, pos1, 10),
      (position_set_y, pos1, 540),
      (overlay_set_position, reg0, pos1),
      (position_set_x, pos1, 500),
      (position_set_y, pos1, 500),
      (overlay_set_size, reg0, pos1),

      (str_store_faction_name, s2, ":npc_faction"),
      (create_text_overlay, reg1, "@{s2}", tf_scrollable_style_2),
      (position_set_x, pos1, 535),
      (position_set_y, pos1, 50),
      (overlay_set_position, reg1, pos1),
      (position_set_x, pos1, 415),
      (position_set_y, pos1, 450+200),
      (overlay_set_area_size, reg1, pos1),
      (set_container_overlay, reg1),
      (set_container_overlay, -1),

      (try_begin),
        (eq, "$g_campaign_type", 0),
        (create_text_overlay, reg1, "@Character information", tf_with_outline),
        (overlay_set_color, reg1, 0xFF4444),
        (position_set_x, pos1, 1000),
        (position_set_y, pos1, 1000),
        (overlay_set_size, reg1, pos1),
        (position_set_x, pos1, 295),
        (position_set_y, pos1, 710),
        (overlay_set_position, reg1, pos1),

        (str_clear, s0),
        (create_text_overlay, reg1, s0, tf_scrollable_style_2),
        (position_set_x, pos1, 225),
        (position_set_y, pos1, 550),
        (overlay_set_position, reg1, pos1),
        (position_set_x, pos1, 260),
        (position_set_y, pos1, 150),
        (overlay_set_area_size, reg1, pos1),
        (set_container_overlay, reg1),

        #get number of lines
        (assign, ":line_number", 0),
        (try_for_range, ":npc", active_npcs_begin, kingdom_ladies_end),
          (call_script, "script_troop_get_family_relation_to_troop", ":npc", "$temp_troop"),
          (gt, reg0, 0),
          (val_add, ":line_number", 1),
        (try_end),
        (val_add, ":line_number", 1),
        (store_mul, ":cur_y", ":line_number", 27),

        (try_for_range, ":npc", active_npcs_begin, kingdom_ladies_end),
          (call_script, "script_troop_get_family_relation_to_troop", ":npc", "$temp_troop"),
          (gt, reg0, 0),
          (str_store_troop_name, s1, ":npc"),
          (create_text_overlay, reg1, "@{s1} ({s11})", 0),
          (position_set_x, pos1, 900),
          (position_set_y, pos1, 900),
          (overlay_set_size, reg1, pos1),
          (position_set_x, pos1, 25),
          (position_set_y, pos1, ":cur_y"),
          (overlay_set_position, reg1, pos1),
          (val_sub, ":cur_y", 27),
        (try_end),

        (troop_get_slot, reg1, "$temp_troop", slot_troop_age),
        (create_text_overlay, reg1, "@Age: {reg1}", 0),
        (position_set_x, pos1, 900),
        (position_set_y, pos1, 900),
        (overlay_set_size, reg1, pos1),
        (position_set_x, pos1, 25),
        (position_set_y, pos1, ":cur_y"),
        (overlay_set_position, reg1, pos1),

        (set_container_overlay, -1),
      (try_end),
    (try_end),

    # Return button
    (create_game_button_overlay, reg1, "@Return"),
    (position_set_x, pos1, 300),
    (position_set_y, pos1, 10),
    (overlay_set_position, reg1, pos1),
    (assign, "$g_jrider_faction_report_return_to_menu", reg1),

    # Continue button
    (create_game_button_overlay, reg1, "@Continue"),
    (position_set_x, pos1, 700),
    (position_set_y, pos1, 10),
    (overlay_set_position, reg1, pos1),
    (assign, "$g_jrider_faction_filter", reg1),

    (create_text_overlay, reg1, "@Rulers:", tf_left_align),
    (position_set_x, pos1, 25),
    (position_set_y, pos1, 510),
    (overlay_set_position, reg1, pos1),
    (overlay_set_color, reg1, 0x99CCFF),
    (position_set_x, pos1, 900),
    (position_set_y, pos1, 900),
    (overlay_set_size, reg1, pos1),

    # scrollable area with ruler grid
    (str_clear, s0),
    (create_text_overlay, reg1, s0, tf_scrollable_style_2),
    (position_set_x, pos1, 50),
    (position_set_y, pos1, 50),
    (overlay_set_position, reg1, pos1),
    (position_set_x, pos1, 450),
    (position_set_y, pos1, 450),
    (overlay_set_area_size, reg1, pos1),

    (store_div, ":y_name", ":num_lords", 2),
    (val_mul, ":y_name", 225),
    (assign, ":x_name", 20),
    (position_set_x, pos2, 900),
    (position_set_y, pos2, 900),

    (set_container_overlay, reg1), #start scroll
    (try_for_range, ":slot", 1, 30),
      (troop_get_slot, ":faction", "trp_temp_array_a", ":slot"),
      (gt, ":faction", -1),
      (faction_get_slot, ":active_npc", ":faction", slot_faction_leader),
      (is_between, ":active_npc", kings_begin, kingdom_ladies_end),
      (neq, "$temp_troop", ":active_npc"),
      (try_begin),
        (ge, ":x_name", 460),
        (assign, ":x_name", 0),
        (val_sub, ":y_name", 220),
      (try_end),

      (create_mesh_overlay_with_tableau_material, reg0, -1, "tableau_troop_note_mesh", ":active_npc"),
      (position_set_x, pos1, ":x_name"),
      (position_set_y, pos1, ":y_name"),
      (overlay_set_position, reg0, pos1),
      (position_set_x, pos3, 500),
      (position_set_y, pos3, 500),
      (overlay_set_size, reg0, pos3),

      # transparent click button
      (create_image_button_overlay, reg10, "mesh_longer_button", "mesh_longer_button"),
      (overlay_set_position, reg10, pos1),
      (position_set_x, pos3, 1000),
      (position_set_y, pos3, 2000),
      (overlay_set_size, reg10, pos3),
      (overlay_set_alpha, reg10, 0),
      (troop_set_slot, "trp_temp_array_b", ":slot", reg10),

      (str_store_troop_name, s0, ":active_npc"),
      (create_text_overlay, reg1, "str_s0", tf_left_align),
      (position_set_x, pos1, ":x_name"),
      (store_sub, ":y_new", ":y_name", 20),
      (position_set_y, pos1, ":y_new"),
      (overlay_set_position, reg1, pos1),
      (overlay_set_size, reg1, pos2),

      (str_store_faction_name, s21, ":faction"),
      (create_text_overlay, reg1, "@{s21}", tf_left_align),
      (position_set_x, pos1, ":x_name"),
      (store_sub, ":y_new", ":y_name", 40),
      (position_set_y, pos1, ":y_new"),
      (overlay_set_position, reg1, pos1),
      (overlay_set_size, reg1, pos2),

      (val_add, ":x_name", 230),
    (try_end),
    (set_container_overlay, -1), #end scroll
  ]),
  ## Check for buttonpress
  (ti_on_presentation_event_state_change,[
    (store_trigger_param_1, ":button_pressed_id"),
    (store_trigger_param_2, ":value"),
    (try_begin),
      (eq, ":button_pressed_id", "$g_jrider_faction_report_return_to_menu"), # Return
      (jump_to_menu, "mnu_start_game_0"),
      (presentation_set_duration, 0),
    (else_try),
      (assign, ":end", 30),
      (try_for_range, ":slot", 1, ":end"),
        (troop_slot_eq, "trp_temp_array_b", ":slot", ":button_pressed_id"),
        (troop_get_slot, ":faction", "trp_temp_array_a", ":slot"),
        (assign, ":end", -1),
      (try_end),
      (eq, ":end", -1),
      (faction_get_slot, "$temp_troop", ":faction", slot_faction_leader),
      (start_presentation, "prsnt_select_kingdom"),
    (else_try),
      (eq, ":button_pressed_id", "$g_jrider_faction_filter"), # Continue
      (try_begin),
        (is_between, "$temp_troop", kings_begin, kingdom_ladies_end),
        # ROYAL: fully become the selected king (name/face/stats/gold/renown/equipment/fiefs)
        (store_troop_faction, ":faction", "$temp_troop"),
        (call_script, "script_player_replace_king", ":faction", 1),
        # spawn the player party near the faction capital (old king's first town)
        (try_begin),
          (is_between, "$g_starting_town", towns_begin, towns_end),
          (assign, "$current_town", "$g_starting_town"),
          (call_script, "script_player_arrived"),
          (party_set_morale, "p_main_party", 100),
          (assign, ":max_dist", 0),
          (party_get_position, pos1, "$g_starting_town"),
          (try_for_range, ":unused", 0, 10),
            (map_get_random_position_around_position, pos0, pos1, 2),
            (get_distance_between_positions, ":dist", pos0, pos1),
            (ge, ":dist", ":max_dist"),
            (assign, ":max_dist", ":dist"),
            (copy_position, pos2, pos0),
          (try_end),
          (party_set_position, "p_main_party", pos2),
        (try_end),
        (assign, "$g_sandbox_start_done", 3), # start_phase_2 shows the capital option instead of towns
        # identity is final: skip gender/background/face chain, go straight to the capital choice
        (jump_to_menu, "mnu_start_phase_2"),
        (presentation_set_duration, 0),
      (else_try),
        (display_message, "@Select a ruler!", 0xFF4444),
      (try_end),
    (try_end),
  ]),
]),
]
