from header_common import *
from header_presentations import *
from header_mission_templates import *
from ID_meshes import *
from header_operations import *
from header_triggers import *
from module_constants import *
import string

from header_skills import *
from header_items import *
from module_items import *
from module_factions import *
from ID_factions import *
from header_triggers import *
from module_my_mod_set import *
from header_terrain_types import *

sandbox_presentations = [

("44", 0, "mesh_load_window", [
    (ti_on_presentation_load, [
        (try_begin),
            (is_edit_mode_enabled),
            (display_message, "@Edit mode is enabled, it is recommended to disable it for better performance.", 10255360),
        (try_end),
        (presentation_set_duration, 999999),
        (set_fixed_point_multiplier, 1000),
        (create_mesh_overlay, reg0, "mesh_pic_extra_intro2"),
        (position_set_x, pos1, -1),
        (position_set_y, pos1, -1),
        (overlay_set_position, reg0, pos1),
        (position_set_x, pos1, 1002),
        (position_set_y, pos1, 1002),
        (overlay_set_size, reg0, pos1),
        (position_set_y, pos1, 25),
        (create_game_button_overlay, "$g_presentation_obj_1", "str_continue"),
        (position_set_x, pos1, 825),
        (overlay_set_position, "$g_presentation_obj_1", pos1),
        (create_game_button_overlay, "$g_presentation_obj_2", "@Diplomacy Options"),
        (position_set_x, pos1, 625),
        (overlay_set_position, "$g_presentation_obj_2", pos1),
        (create_game_button_overlay, "$g_presentation_obj_5", "@Battle-Morale Options"),
        (position_set_x, pos1, 425),
        (overlay_set_position, "$g_presentation_obj_5", pos1),
        (try_begin),
            (eq, reg60, 1),
            (create_game_button_overlay, "$g_presentation_obj_19", "str_back"),
            (position_set_x, pos1, 225),
            (overlay_set_position, "$g_presentation_obj_19", pos1),
        (try_end),
        (try_begin),
            (eq, reg60, 1),
            (create_text_overlay, reg1, "@Welcome to Aut Caesar aut nihil. ^Before you start the game, choose various options.^Note that realistic savings are always disabled!", 65552),
            (overlay_set_color, reg1, 127),
            (position_set_x, pos1, 250),
            (position_set_y, pos1, 670),
            (overlay_set_position, reg1, pos1),
            (position_set_x, pos1, 1200),
            (position_set_y, pos1, 1200),
            (overlay_set_size, reg1, pos1),
        (try_end),
        (create_text_overlay, reg1, "@Settlement names", 65552),
        (overlay_set_color, reg1, 8398162),
        (position_set_x, pos1, 250),
        (position_set_y, pos1, 645),
        (overlay_set_position, reg1, pos1),
        (position_set_x, pos1, 1200),
        (position_set_y, pos1, 1200),
        (overlay_set_size, reg1, pos1),
        (create_combo_button_overlay, "$g_presentation_obj_admin_panel_6"),
        (position_set_x, pos1, 250),
        (position_set_y, pos1, 605),
        (overlay_set_position, "$g_presentation_obj_admin_panel_6", pos1),
        (try_begin),
            (eq, reg60, 0),
            (overlay_set_alpha, "$g_presentation_obj_admin_panel_6", 160),
            (try_begin),
                (eq, "$g_province_names", 1),
                (overlay_add_item, "$g_presentation_obj_admin_panel_6", "@Accurate Province Names"),
            (else_try),
                (eq, "$g_province_names", 2),
                (overlay_add_item, "$g_presentation_obj_admin_panel_6", "@Simple Province Names"),
            (else_try),
                (overlay_add_item, "$g_presentation_obj_admin_panel_6", "@Normal Names"),
            (try_end),
        (else_try),
            (overlay_add_item, "$g_presentation_obj_admin_panel_6", "@Simple Province Names"),
            (overlay_add_item, "$g_presentation_obj_admin_panel_6", "@Accurate Province Names"),
            (overlay_add_item, "$g_presentation_obj_admin_panel_6", "@Normal Names"),
            (try_begin),
                (eq, "$g_province_names", 2),
                (overlay_set_val, "$g_presentation_obj_admin_panel_6", 0),
            (else_try),
                (eq, "$g_province_names", 1),
                (overlay_set_val, "$g_presentation_obj_admin_panel_6", 1),
            (else_try),
                (overlay_set_val, "$g_presentation_obj_admin_panel_6", 2),
            (try_end),
        (try_end),
        (try_begin),
            (troop_slot_ge, "trp_global_variables", 0, 1),
            (create_text_overlay, reg1, "@Campaign type", 65552),
            (overlay_set_color, reg1, 8398162),
            (position_set_x, pos1, 250),
            (position_set_y, pos1, 555),
            (overlay_set_position, reg1, pos1),
            (position_set_x, pos1, 1200),
            (position_set_y, pos1, 1200),
            (overlay_set_size, reg1, pos1),
            (create_combo_button_overlay, "$g_presentation_obj_admin_panel_9"),
            (position_set_x, pos1, 250),
            (position_set_y, pos1, 515),
            (overlay_set_position, "$g_presentation_obj_admin_panel_9", pos1),
            (try_begin),
                (eq, reg60, 0),
                (overlay_set_alpha, "$g_presentation_obj_admin_panel_9", 160),
                (try_begin),
                    (eq, "$g_campaign_type", 3),
                    (overlay_add_item, "$g_presentation_obj_admin_panel_9", "@STORY: SON OF ROME"),
                (else_try),
                    (eq, "$g_campaign_type", 0),
                    (overlay_add_item, "$g_presentation_obj_admin_panel_9", "@ROYAL SANDBOX"),
                (else_try),
                    (eq, "$g_campaign_type", 1),
                    (overlay_add_item, "$g_presentation_obj_admin_panel_9", "@LORDLY SANDBOX"),
                (else_try),
                    (eq, "$g_campaign_type", 2),
                    (overlay_add_item, "$g_presentation_obj_admin_panel_9", "@SANDBOX"),
                (try_end),
            (else_try),
                (overlay_add_item, "$g_presentation_obj_admin_panel_9", "@ROYAL SANDBOX"),
                (overlay_add_item, "$g_presentation_obj_admin_panel_9", "@LORDLY SANDBOX"),
                (overlay_add_item, "$g_presentation_obj_admin_panel_9", "@SANDBOX"),
                (overlay_add_item, "$g_presentation_obj_admin_panel_9", "@STORY: SON OF ROME"),
                (try_begin),
                    (eq, "$g_campaign_type", 0),
                    (overlay_set_val, "$g_presentation_obj_admin_panel_9", 0),
                (else_try),
                    (eq, "$g_campaign_type", 1),
                    (overlay_set_val, "$g_presentation_obj_admin_panel_9", 1),
                (else_try),
                    (eq, "$g_campaign_type", 2),
                    (overlay_set_val, "$g_presentation_obj_admin_panel_9", 2),
                (else_try),
                    (eq, "$g_campaign_type", 3),
                    (overlay_set_val, "$g_presentation_obj_admin_panel_9", 3),
                (try_end),
            (try_end),
        (try_end),
        (create_text_overlay, reg1, "@Difficulty Type", 65552),
        (overlay_set_color, reg1, 8398162),
        (position_set_x, pos1, 250),
        (position_set_y, pos1, 465),
        (overlay_set_position, reg1, pos1),
        (position_set_x, pos1, 1200),
        (position_set_y, pos1, 1200),
        (overlay_set_size, reg1, pos1),
        (create_combo_button_overlay, "$g_presentation_obj_6"),
        (position_set_x, pos1, 250),
        (position_set_y, pos1, 425),
        (overlay_set_position, "$g_presentation_obj_6", pos1),
        (overlay_add_item, "$g_presentation_obj_6", "@ACAN GIGA CHAD"),
        (overlay_add_item, "$g_presentation_obj_6", "@ACAN CHAD"),
        (overlay_add_item, "$g_presentation_obj_6", "@BORING (NORMAL)"),
        (overlay_add_item, "$g_presentation_obj_6", "@DISCORD SCHIZO"),
        (overlay_add_item, "$g_presentation_obj_6", "@LOSER (CUSTOM)"),
        (try_begin),
            (eq, "$difficulty_type", 15),
            (overlay_set_val, "$g_presentation_obj_6", 0),
        (else_try),
            (eq, "$difficulty_type", 14),
            (overlay_set_val, "$g_presentation_obj_6", 1),
        (else_try),
            (eq, "$difficulty_type", 13),
            (overlay_set_val, "$g_presentation_obj_6", 2),
        (else_try),
            (eq, "$difficulty_type", 12),
            (overlay_set_val, "$g_presentation_obj_6", 3),
        (else_try),
            (eq, "$difficulty_type", 11),
            (overlay_set_val, "$g_presentation_obj_6", 4),
        (try_end),
        (create_text_overlay, reg1, "@Options", 65552),
        (overlay_set_color, reg1, 8398162),
        (position_set_x, pos1, 750),
        (position_set_y, pos1, 650),
        (overlay_set_position, reg1, pos1),
        (position_set_x, pos2, 1200),
        (position_set_y, pos2, 1200),
        (overlay_set_size, reg1, pos2),
        (str_clear, s0),
        (create_text_overlay, "$g_presentation_obj_admin_panel_container", 0, 8192),
        (position_set_x, pos1, 575),
        (position_set_y, pos1, 90),
        (overlay_set_position, "$g_presentation_obj_admin_panel_container", pos1),
        (position_set_x, pos1, 350),
        (position_set_y, pos1, 535),
        (overlay_set_area_size, "$g_presentation_obj_admin_panel_container", pos1),
        (set_container_overlay, "$g_presentation_obj_admin_panel_container"),
        (position_set_x, pos1, 0),
        (position_set_y, pos1, 1100),
        (try_begin),
            (eq, reg60, 1),
            (position_get_y, ":var_0", pos1),
            (val_add, ":var_0", 35),
            (position_set_y, pos1, ":var_0"),
            (create_text_overlay, reg1, "@These options can be changed later in the camp menu.^The Diplomacy preferences can be found in the camp menu too.", 10256),
            (copy_position, pos2, pos1),
            (overlay_set_position, reg1, pos2),
            (position_set_x, pos2, 350),
            (position_set_y, pos2, 60),
            (overlay_set_area_size, reg1, pos2),
            (position_set_x, pos2, 900),
            (position_set_y, pos2, 900),
            (overlay_set_size, reg1, pos2),
            (position_get_y, ":var_0", pos1),
            (val_sub, ":var_0", 35),
            (position_set_y, pos1, ":var_0"),
        (try_end),
        (create_text_overlay, reg1, "str_damage_to_player", 0),
        (call_script, "prsnt_vc_menu_helper_2"),
        (overlay_add_item, reg2, "@Reduced to 1/4 (Easiest)"),
        (overlay_add_item, reg2, "@Reduced to 1/2 (Easy)"),
        (overlay_add_item, reg2, "str_normal"),
        (options_get_damage_to_player, reg8),
        (overlay_set_val, reg2, reg8),
        (assign, "$g_presentation_obj_25", reg2),
        (create_text_overlay, reg1, "str_damage_to_friends", 0),
        (call_script, "prsnt_vc_menu_helper_2"),
        (overlay_add_item, reg2, "@Reduced to 1/2 (Easiest)"),
        (overlay_add_item, reg2, "@Reduced to 3/4 (Easy)"),
        (overlay_add_item, reg2, "str_normal"),
        (options_get_damage_to_friends, reg8),
        (overlay_set_val, reg2, reg8),
        (assign, "$g_presentation_obj_26", reg2),
        (call_script, "prsnt_vc_menu_helper_gap"),
        (create_text_overlay, reg1, "str_combat_ai", 0),
        (call_script, "prsnt_vc_menu_helper_2"),
        (overlay_add_item, reg2, "str_hardcore"),
        (overlay_add_item, reg2, "str_normal"),
        (overlay_add_item, reg2, "str_beginner"),
        (options_get_combat_ai, reg8),
        (overlay_set_val, reg2, reg8),
        (assign, "$g_presentation_obj_27", reg2),
        (create_text_overlay, reg1, "str_movement_and_combat_speed", 0),
        (call_script, "prsnt_vc_menu_helper_2"),
        (overlay_add_item, reg2, "@Slowest"),
        (overlay_add_item, reg2, "@Slower"),
        (overlay_add_item, reg2, "str_normal"),
        (overlay_add_item, reg2, "@Faster"),
        (overlay_add_item, reg2, "@Fastest"),
        (options_get_combat_speed, reg8),
        (overlay_set_val, reg2, reg8),
        (assign, "$g_presentation_obj_29", reg2),
        (create_text_overlay, reg1, "str_campaign_ai", 0),
        (call_script, "prsnt_vc_menu_helper_2"),
        (overlay_add_item, reg2, "str_hardcore"),
        (overlay_add_item, reg2, "str_normal"),
        (overlay_add_item, reg2, "str_beginner"),
        (options_get_campaign_ai, reg8),
        (overlay_set_val, reg2, reg8),
        (assign, "$g_presentation_obj_28", reg2),
        (call_script, "prsnt_vc_menu_helper_gap"),
        (create_text_overlay, reg1, "@Warcry", 0),
        (call_script, "prsnt_vc_menu_helper"),
        (overlay_set_val, reg2, "$g_charge_on"),
        (assign, "$g_presentation_obj_14", reg2),
        (create_text_overlay, reg1, "@Player auxiliary feature", 0),
        (call_script, "prsnt_vc_menu_helper"),
        (overlay_set_val, reg2, "$use_player_auxiliary"),
        (assign, "$g_presentation_obj_15", reg2),
        (create_text_overlay, reg1, "@Autoloot", 0),
        (call_script, "prsnt_vc_menu_helper"),
        (overlay_set_val, reg2, "$g_autoloot_active"),
        (assign, "$g_presentation_obj_20", reg2),
        (create_text_overlay, reg1, "@Realistic troop wounding", 0),
        (call_script, "prsnt_vc_menu_helper"),
        (overlay_set_val, reg2, "$g_realistic_wounding"),
        (assign, "$g_presentation_obj_31", reg2),
        (create_text_overlay, reg1, "str_wounds", 0),
        (call_script, "prsnt_vc_menu_helper"),
        (overlay_set_val, reg2, "$vc_wounds_on"),
        (assign, "$g_presentation_obj_33", reg2),
        (create_text_overlay, reg1, "str_resting_morale", 0),
        (call_script, "prsnt_vc_menu_helper"),
        (overlay_set_val, reg2, "$moralep_on"),
        (assign, "$g_presentation_obj_16", reg2),
        (create_text_overlay, reg1, "@Bodyguards", 0),
        (call_script, "prsnt_vc_menu_helper"),
        (overlay_set_val, reg2, "$g_body_guard_on"),
        (assign, "$g_presentation_obj_admin_panel_8", reg2),
        (create_text_overlay, reg1, "@Shieldbash", 0),
        (call_script, "prsnt_vc_menu_helper"),
        (overlay_set_val, reg2, "$g_schield_bash"),
        (assign, "$g_presentation_obj_admin_panel_2", reg2),
        (call_script, "prsnt_vc_menu_helper_gap"),
        (create_text_overlay, reg1, "@Governor/lord appointment notification", 0),
        (call_script, "prsnt_vc_menu_helper"),
        (overlay_set_val, reg2, "$g_governor_appointment_message"),
        (assign, "$g_presentation_obj_admin_panel_7", reg2),
        (create_text_overlay, reg1, "@Truce notification menus", 0),
        (call_script, "prsnt_vc_menu_helper"),
        (overlay_set_val, reg2, "$show_truce_expired"),
        (assign, "$g_presentation_obj_32", reg2),
        (create_text_overlay, reg1, "@Raid notification menus", 0),
        (call_script, "prsnt_vc_menu_helper"),
        (overlay_set_val, reg2, "$show_raid_messages"),
        (assign, "$form_options_overlay_2", reg2),
        (create_text_overlay, reg1, "@Lovers discovered notifications", 0),
        (call_script, "prsnt_vc_menu_helper"),
        (overlay_set_val, reg2, "$g_love_messages_on"),
        (assign, "$g_presentation_obj_11", reg2),
        (create_text_overlay, reg1, "@Senate meetings notifications", 0),
        (call_script, "prsnt_vc_menu_helper"),
        (overlay_set_val, reg2, "$g_show_senate_meeting"),
        (assign, "$g_presentation_obj_9", reg2),
        (create_text_overlay, reg1, "@Enemies spotted notifications", 0),
        (call_script, "prsnt_vc_menu_helper"),
        (overlay_set_val, reg2, "$g_report_enemies"),
        (assign, "$g_presentation_obj_admin_panel_4", reg2),
        (create_text_overlay, reg1, "@Lord gifts notifications", 0),
        (call_script, "prsnt_vc_menu_helper"),
        (overlay_set_val, reg2, "$g_display_gift"),
        (assign, "$g_presentation_obj_24", reg2),
        (call_script, "prsnt_vc_menu_helper_gap"),
        (create_text_overlay, reg1, "str_battle_size", 0),
        (call_script, "prsnt_vc_menu_helper_3"),
        (options_get_battle_size, reg8),
        (overlay_set_val, reg2, reg8),
        (assign, "$g_presentation_obj_30", reg2),
        (call_script, "prsnt_vc_menu_helper_gap"),
        (create_text_overlay, reg1, "str_insane_difficult", 0),
        (call_script, "prsnt_vc_menu_helper"),
        (overlay_set_val, reg2, "$insanedamage_on"),
        (assign, "$g_presentation_obj_17", reg2),
        (create_text_overlay, reg1, "str_gore", 0),
        (call_script, "prsnt_vc_menu_helper"),
        (overlay_set_val, reg2, "$g_gore_on"),
        (assign, "$g_presentation_obj_18", reg2),
        (call_script, "prsnt_vc_menu_helper_gap"),
        (create_text_overlay, reg1, "str_player_division", 0),
        (call_script, "prsnt_vc_menu_helper_2"),
        (try_for_range, ":var_1", -1, 9),
            (try_begin),
                (eq, ":var_1", -1),
                (overlay_add_item, reg2, "str_none"),
            (else_try),
                (str_store_class_name, s7, ":var_1"),
                (overlay_add_item, reg2, s7),
            (try_end),
        (try_end),
        (overlay_set_val, reg2, "$form_ai_player_in_division"),
        (assign, "$form_options_overlay_1", reg2),
        (create_text_overlay, reg1, "str_disable_complex_formations", 0),
        (call_script, "prsnt_vc_menu_helper"),
        (overlay_set_val, reg2, "$form_ai_off"),
        (assign, "$g_presentation_obj_21", reg2),
        (create_text_overlay, reg1, "str_have_formations_face_enemy", 0),
        (call_script, "prsnt_vc_menu_helper"),
        (overlay_set_val, reg2, "$form_ai_autorotate"),
        (assign, "$g_presentation_obj_22", reg2),
        (set_container_overlay, -1),
        (create_text_overlay, reg1, "str_empty_string", 16),
        (position_set_x, pos1, 250),
        (position_set_y, pos1, 370),
        (overlay_set_position, reg1, pos1),
        (position_set_x, pos1, 1200),
        (position_set_y, pos1, 1200),
        (overlay_set_size, reg1, pos1),
        (assign, "$g_presentation_obj_3", reg1),
        (create_text_overlay, reg1, "str_empty_string", 10256),
        (position_set_x, pos1, 75),
        (position_set_y, pos1, 100),
        (overlay_set_position, reg1, pos1),
        (position_set_x, pos1, 350),
        (position_set_y, pos1, 260),
        (overlay_set_area_size, reg1, pos1),
        (position_set_x, pos1, 900),
        (position_set_y, pos1, 900),
        (overlay_set_size, reg1, pos1),
        (assign, "$g_presentation_obj_7", reg1),
        (str_store_string, s3, "str_continue"),
        (create_text_overlay, reg1, "@Warning: This option can't be disabled any more after you click '{s3}.'", 75792),
        (position_set_x, pos1, 75),
        (position_set_y, pos1, 90),
        (overlay_set_position, reg1, pos1),
        (position_set_x, pos1, 350),
        (position_set_y, pos1, 70),
        (overlay_set_area_size, reg1, pos1),
        (position_set_x, pos1, 900),
        (position_set_y, pos1, 900),
        (overlay_set_size, reg1, pos1),
        (overlay_set_color, reg1, 16733525),
        (assign, "$g_presentation_obj_4", reg1),
        (overlay_set_display, "$g_presentation_obj_4", 0),
    ]),
    (ti_on_presentation_mouse_enter_leave, [
        (store_trigger_param_1, ":var_0"),
        (store_trigger_param_2, ":var_1"),
        (str_clear, s2),
        (str_clear, s3),
        (str_clear, s4),
        (overlay_set_color, "$g_presentation_obj_3", 0),
        (try_begin),
            (eq, ":var_1", 1),
        (else_try),
            (eq, ":var_0", "$g_presentation_obj_6"),
            (str_store_string, s2, "@Choose a difficulty type!"),
        (else_try),
            (store_add, ":var_2", ":var_0", 1),
            (this_or_next|eq, ":var_2", "$g_presentation_obj_11"),
            (eq, ":var_0", "$g_presentation_obj_11"),
            (str_store_string, s2, "@Notification about discovered love affairs"),
            (str_store_string, s3, "str_qual_life_feature"),
            (str_store_string, s4, "@If enabled, you will receive messages about discovered love affairs, even if you are not involved."),
            (overlay_set_display, "$g_presentation_obj_4", 0),
        (else_try),
            (this_or_next|eq, ":var_2", "$g_presentation_obj_14"),
            (eq, ":var_0", "$g_presentation_obj_14"),
            (str_store_string, s2, "@Warcry"),
            (str_store_string, s3, "str_immersion_feature"),
            (str_store_string, s8, "@Effects player and allies during battles"),
            (str_store_string, s4, "@When the player makes a warcry (T-key), the player agents performe a cheer animation.^^{s8}"),
            (overlay_set_display, "$g_presentation_obj_4", 0),
        (else_try),
            (this_or_next|eq, ":var_2", "$g_presentation_obj_15"),
            (eq, ":var_0", "$g_presentation_obj_15"),
            (str_store_string, s2, "@Auxiliar player feature"),
            (str_store_string, s3, "str_immersion_feature"),
            (str_store_string, s8, "@Effects player after death"),
            (str_store_string, s4, "@Instead of the death camera, the player takes over the control of a troop from his own party, who is still alive.^^{s8}"),
            (overlay_set_display, "$g_presentation_obj_4", 0),
        (else_try),
            (this_or_next|eq, ":var_2", "$g_presentation_obj_16"),
            (eq, ":var_0", "$g_presentation_obj_16"),
            (str_store_string, s2, "str_resting_morale"),
            (str_store_string, s3, "str_realism_feature"),
            (str_store_string, s4, "@Your army needs regular rest in a settlement or your camp site from time to time. Lack of rest will lower your troop morale, while resting will improve it. Resting at camps isn't as good as resting in settlements, while resting in settlements your party will recieve an additional morale boost."),
            (overlay_set_display, "$g_presentation_obj_4", 0),
        (else_try),
            (this_or_next|eq, ":var_2", "$g_presentation_obj_17"),
            (eq, ":var_0", "$g_presentation_obj_17"),
            (str_store_string, s2, "str_insane_difficult"),
            (str_store_string, s3, "str_special_setting"),
            (str_store_string, s4, "@Your enemies will cause double damage while you cause only half."),
            (overlay_set_display, "$g_presentation_obj_4", 0),
        (else_try),
            (this_or_next|eq, ":var_2", "$g_presentation_obj_18"),
            (eq, ":var_0", "$g_presentation_obj_18"),
            (str_store_string, s2, "str_gore"),
            (str_store_string, s3, "str_special_setting"),
            (str_store_string, s4, "@Add decapitation to battles."),
            (overlay_set_display, "$g_presentation_obj_4", 0),
        (else_try),
            (this_or_next|eq, ":var_2", "$g_presentation_obj_20"),
            (eq, ":var_0", "$g_presentation_obj_20"),
            (str_store_string, s2, "@Autoloot"),
            (str_store_string, s3, "str_qual_life_feature"),
            (str_store_string, s4, "@If enabled, you can, if your inventory management or looting skill is higher than 2, manage the equipement of you companions automatically."),
            (overlay_set_display, "$g_presentation_obj_4", 0),
        (else_try),
            (this_or_next|eq, ":var_2", "$g_presentation_obj_21"),
            (eq, ":var_0", "$g_presentation_obj_21"),
            (str_store_string, s2, "str_disable_complex_formations"),
            (str_store_string, s3, "str_formation_feature"),
            (str_store_string, s4, "@The divisions of the player's army will not adopt the formations of shield wall, wedge, or square. Moreover, the F4 menu that contains these selections will no longer appear.^^The default ranks formations will always be adopted when the player closes ranks beyond the point needed to make a shoulder-to-shoulder line."),
            (overlay_set_display, "$g_presentation_obj_4", 0),
        (else_try),
            (this_or_next|eq, ":var_2", "$g_presentation_obj_22"),
            (eq, ":var_0", "$g_presentation_obj_22"),
            (str_store_string, s2, "str_have_formations_face_enemy"),
            (str_store_string, s3, "str_formation_feature"),
            (str_store_string, s4, "@When multiple divisions are placed, they will set up to face the center of the enemy forces. Without this option, they will set up along the facing that the player has when he/she places them, although individual divisions will still turn to face the enemy.^^For example, with the option OFF and the player facing AWAY from the attacker, infantry will set up on the RIGHT flank rather than the LEFT."),
            (overlay_set_display, "$g_presentation_obj_4", 0),
        (else_try),
            (this_or_next|eq, ":var_2", "$g_presentation_obj_25"),
            (eq, ":var_0", "$g_presentation_obj_25"),
            (str_store_string, s2, "str_damage_to_player"),
            (str_store_string, s3, "str_difficulty_setting"),
            (str_store_string, s4, "@Set how much damage is done to your character."),
            (overlay_set_display, "$g_presentation_obj_4", 0),
        (else_try),
            (this_or_next|eq, ":var_2", "$g_presentation_obj_26"),
            (eq, ":var_0", "$g_presentation_obj_26"),
            (str_store_string, s2, "str_damage_to_friends"),
            (str_store_string, s3, "str_difficulty_setting"),
            (str_store_string, s4, "@Set how much damage is done to your army."),
            (overlay_set_display, "$g_presentation_obj_4", 0),
        (else_try),
            (this_or_next|eq, ":var_2", "$g_presentation_obj_27"),
            (eq, ":var_0", "$g_presentation_obj_27"),
            (str_store_string, s2, "str_combat_ai"),
            (str_store_string, s3, "str_difficulty_setting"),
            (str_store_string, s4, "@Set how well troops fight. They fight worst at Beginner level."),
            (overlay_set_display, "$g_presentation_obj_4", 0),
        (else_try),
            (this_or_next|eq, ":var_2", "$g_presentation_obj_28"),
            (eq, ":var_0", "$g_presentation_obj_28"),
            (str_store_string, s2, "str_campaign_ai"),
            (str_store_string, s3, "str_difficulty_setting"),
            (str_store_string, s4, "@Effects size of bandit parties:^^-) Poor: 50% Size.^^-) Average: 75% Size.^^-) Good: 100% Size. THIS DOES NOT EFFECT EXISTING PARTIES!"),
            (overlay_set_display, "$g_presentation_obj_4", 0),
        (else_try),
            (this_or_next|eq, ":var_2", "$g_presentation_obj_29"),
            (eq, ":var_0", "$g_presentation_obj_29"),
            (str_store_string, s2, "str_movement_and_combat_speed"),
            (str_store_string, s3, "str_difficulty_setting"),
            (str_store_string, s8, "str_this_setting_affects_all"),
            (str_store_string, s4, "@Set the running speed of troops in battle.^^{s8}"),
            (overlay_set_display, "$g_presentation_obj_4", 0),
        (else_try),
            (this_or_next|eq, ":var_2", "$g_presentation_obj_30"),
            (eq, ":var_0", "$g_presentation_obj_30"),
            (str_store_string, s2, "str_battle_size"),
            (str_store_string, s3, "str_performance_feature"),
            (call_script, "current_battle_size"),
            (str_store_string, s2, "@{s2} {reg0}"),
            (str_store_string, s4, "str_battle_size_text"),
            (overlay_set_display, "$g_presentation_obj_4", 0),
            (try_begin),
                (gt, reg0, 300),
                (overlay_set_color, "$g_presentation_obj_3", 16711680),
            (try_end),
        (else_try),
            (this_or_next|eq, ":var_2", "$g_presentation_obj_31"),
            (eq, ":var_0", "$g_presentation_obj_31"),
            (str_store_string, s2, "@Realistic troop wounding"),
            (str_store_string, s3, "@Realism feature"),
            (str_store_string, s4, "@If enabled, troops may not die immediately, but instead get only wounded, depending damage done. If damage done is larger than 40, they will die, even if a blunt weapon was used."),
            (overlay_set_display, "$g_presentation_obj_4", 0),
        (else_try),
            (this_or_next|eq, ":var_2", "$g_presentation_obj_32"),
            (eq, ":var_0", "$g_presentation_obj_32"),
            (str_store_string, s2, "@Truce notification menus"),
            (str_store_string, s3, "str_qual_life_feature"),
            (str_store_string, s4, "@If enabled, you will recieve notification menus, about alliances, defensive pacts, non-aggression pacts, trade agreements and truces which have expired."),
            (overlay_set_display, "$g_presentation_obj_4", 0),
        (else_try),
            (this_or_next|eq, ":var_2", "$g_presentation_obj_33"),
            (eq, ":var_0", "$g_presentation_obj_33"),
            (str_store_string, s2, "str_wounds"),
            (str_store_string, s3, "str_realism_feature"),
            (str_store_string, s4, "@The player may receive specific, debilitating wounds in battle. Physicians in larger towns will treat these wounds for a price, after which they will heal within a few days. Any negative effects will then be removed. If wound is not treated after some time, it will change to a scar, and the negative effects will then be permanent."),
            (overlay_set_display, "$g_presentation_obj_4", 0),
        (else_try),
            (this_or_next|eq, ":var_2", "$form_options_overlay_1"),
            (eq, ":var_0", "$form_options_overlay_1"),
            (str_store_string, s2, "str_player_division"),
            (str_store_string, s3, "str_formation_feature"),
            (str_store_string, s4, "@Sets the player as commander of the chosen division. This division will set up immediately left and behind the player on Hold and Follow commands (Wedge will put player on the point). Consider it for bodyguard divisions."),
            (overlay_set_display, "$g_presentation_obj_4", 0),
        (else_try),
            (this_or_next|eq, ":var_2", "$form_options_overlay_2"),
            (eq, ":var_0", "$form_options_overlay_2"),
            (str_store_string, s2, "@Village raid notification menus"),
            (str_store_string, s3, "str_qual_life_feature"),
            (str_store_string, s4, "@If enabled, you recieve notification menus about your villages which has been raided."),
            (overlay_set_display, "$g_presentation_obj_4", 0),
        (else_try),
            (this_or_next|eq, ":var_2", "$g_presentation_obj_9"),
            (eq, ":var_0", "$g_presentation_obj_9"),
            (str_store_string, s2, "@Senate meetings notification menus"),
            (str_store_string, s3, "str_qual_life_feature"),
            (str_store_string, s4, "@If enabled, you recieve notification menus about senate meetings."),
            (overlay_set_display, "$g_presentation_obj_4", 0),
        (else_try),
            (this_or_next|eq, ":var_2", "$g_presentation_obj_admin_panel_8"),
            (eq, ":var_0", "$g_presentation_obj_admin_panel_8"),
            (str_store_string, s2, "@Bodyguards"),
            (str_store_string, s3, "str_qual_life_feature"),
            (str_store_string, s4, "@If enabled, up to four companions will accompany you when you walk in taverns, through the streets etc. Companions spawn according to their position inside the party. Companions ordered first, will spawn first."),
            (overlay_set_display, "$g_presentation_obj_4", 0),
        (else_try),
            (this_or_next|eq, ":var_2", "$g_presentation_obj_admin_panel_7"),
            (eq, ":var_0", "$g_presentation_obj_admin_panel_7"),
            (str_store_string, s2, "@Governor/lord appointment notification"),
            (str_store_string, s3, "str_qual_life_feature"),
            (str_store_string, s4, "@If enabled you will receive messages about the appointment of governors/lords for empty provinces/fiefs. The menu has options for you to use your influence to change the outcome to your liking."),
            (overlay_set_display, "$g_presentation_obj_4", 0),
        (else_try),
            (this_or_next|eq, ":var_2", "$g_presentation_obj_admin_panel_4"),
            (eq, ":var_0", "$g_presentation_obj_admin_panel_4"),
            (str_store_string, s2, "@Enemies spotted messages"),
            (str_store_string, s3, "str_qual_life_feature"),
            (str_store_string, s4, "@If enabled, you will recieve notification if enemies are spotted from nearby settlements or from settlements with messanger posts."),
            (overlay_set_display, "$g_presentation_obj_4", 0),
        (else_try),
            (this_or_next|eq, ":var_2", "$g_presentation_obj_admin_panel_2"),
            (eq, ":var_0", "$g_presentation_obj_admin_panel_2"),
            (str_store_string, s2, "@Shieldbash"),
            (str_store_string, s3, "str_realism_feature"),
            (str_store_string, s4, "@If enabled, Ai and player can perform a shieldbash during battle."),
            (overlay_set_display, "$g_presentation_obj_4", 0),
        (else_try),
            (this_or_next|eq, ":var_2", "$g_presentation_obj_24"),
            (eq, ":var_0", "$g_presentation_obj_24"),
            (str_store_string, s2, "@Lord gift Messages"),
            (str_store_string, s3, "str_qual_life_feature"),
            (str_store_string, s4, "@If enabled you will recieve messages which informs you about gifts a Lord gave his liege."),
            (overlay_set_display, "$g_presentation_obj_4", 0),
        (else_try),
            (this_or_next|eq, ":var_2", "$g_presentation_obj_admin_panel_6"),
            (eq, ":var_0", "$g_presentation_obj_admin_panel_6"),
            (str_store_string, s2, "@Display province names"),
            (str_store_string, s3, "str_qual_life_feature"),
            (str_store_string, s4, "@Normal Names:^Settlements are named like in previous versions.^Accurate Province Names:^In the name of the settlement, the province name is displayed, e.g. Lutetia -> Lutetia (Lugdunensis)^Simple province names:^A simplified, more general, name of the province will be displayed, e.g. Lutetia -> Lutetia (GL), where GL stands for Gaul (abbreviations can be found under game concepts)"),
            (overlay_set_display, "$g_presentation_obj_4", 0),
            (try_begin),
                (eq, reg60, 1),
                (overlay_set_display, "$g_presentation_obj_4", 1),
            (try_end),
        (else_try),
            (this_or_next|eq, ":var_2", "$g_presentation_obj_admin_panel_9"),
            (eq, ":var_0", "$g_presentation_obj_admin_panel_9"),
            (str_store_string, s2, "@Campaign type"),
            (str_store_string, s3, "@Choose a campaign type"),
            (str_store_string, s4, "@Story: Take part in an epic story.^Sandbox: Classic M&B sandbox campaign.^Lordly Sandbox: Sandbox campaign where you start as lord^Royal Sandbox: Sandbox camoaign where you start as king."),
            (overlay_set_display, "$g_presentation_obj_4", 0),
            (try_begin),
                (eq, reg60, 1),
                (overlay_set_display, "$g_presentation_obj_4", 1),
            (try_end),
        (try_end),
        (str_store_string, s3, "@{s3}^^{s4}"),
        (overlay_set_text, "$g_presentation_obj_3", s2),
        (overlay_set_text, "$g_presentation_obj_7", s3),
    ]),
    (ti_on_presentation_event_state_change, [
        (store_trigger_param_1, ":var_0"),
        (store_trigger_param_2, ":var_1"),
        (overlay_set_color, "$g_presentation_obj_3", 0),
        (try_begin),
            (eq, ":var_0", "$g_presentation_obj_1"),
            (presentation_set_duration, 0),
            (try_begin),
                (eq, "$moralep_on", 0),
                (party_set_slot, "p_main_party", 195, 0),
            (try_end),
            (call_script, "dplmc_update_info_settings"),
            (try_begin),
                (eq, reg60, 0),
                (jump_to_menu, "mnu_camp"),
            (else_try),
                (try_begin),
                    (this_or_next|eq, "$g_campaign_type", 0),
                    (this_or_next|eq, "$g_campaign_type", 2),
                    (eq, "$g_campaign_type", 1),
                    (jump_to_menu, "mnu_start_game_sandbox"),
                (else_try),
                    (jump_to_menu, "mnu_start_game_1"),
                (try_end),
            (try_end),
        (else_try),
            (eq, ":var_0", "$g_presentation_obj_2"),
            (start_presentation, "prsnt_43"),
        (else_try),
            (eq, ":var_0", "$g_presentation_obj_5"),
            (start_presentation, "prsnt_45"),
        (else_try),
            (eq, ":var_0", "$g_presentation_obj_19"),
            (jump_to_menu, "mnu_start_game_11"),
        (else_try),
            (eq, ":var_0", "$g_presentation_obj_6"),
            (try_begin),
                (eq, ":var_1", 0),
                (assign, "$difficulty_type", 15),
                (assign, "$g_gore_on", 1),
                (assign, "$g_charge_on", 1),
                (assign, "$use_player_auxiliary", 0),
                (assign, "$g_autoloot_active", 0),
                (assign, "$g_realistic_wounding", 1),
                (assign, "$vc_wounds_on", 1),
                (assign, "$moralep_on", 1),
                (assign, "$g_body_guard_on", 0),
                (assign, "$g_schield_bash", 1),
                (assign, "$g_governor_appointment_message", 1),
                (assign, "$show_truce_expired", 1),
                (assign, "$show_raid_messages", 1),
                (assign, "$g_love_messages_on", 1),
                (assign, "$g_show_senate_meeting", 1),
                (assign, "$g_report_enemies", 1),
                (assign, "$g_display_gift", 1),
                (options_set_damage_to_player, 2),
                (options_set_damage_to_friends, 2),
                (options_set_combat_ai, 0),
                (options_set_campaign_ai, 0),
                (options_set_combat_speed, 4),
            (else_try),
                (eq, ":var_1", 1),
                (assign, "$difficulty_type", 14),
                (assign, "$g_charge_on", 1),
                (assign, "$g_gore_on", 1),
                (assign, "$use_player_auxiliary", 1),
                (assign, "$g_autoloot_active", 1),
                (assign, "$g_realistic_wounding", 1),
                (assign, "$vc_wounds_on", 1),
                (assign, "$moralep_on", 1),
                (assign, "$g_body_guard_on", 1),
                (assign, "$g_schield_bash", 1),
                (assign, "$g_governor_appointment_message", 1),
                (assign, "$show_truce_expired", 0),
                (assign, "$show_raid_messages", 1),
                (assign, "$g_love_messages_on", 1),
                (assign, "$g_show_senate_meeting", 1),
                (assign, "$g_report_enemies", 0),
                (assign, "$g_display_gift", 1),
                (options_set_damage_to_player, 2),
                (options_set_damage_to_friends, 2),
                (options_set_combat_ai, 1),
                (options_set_campaign_ai, 1),
                (options_set_combat_speed, 3),
            (else_try),
                (eq, ":var_1", 2),
                (assign, "$difficulty_type", 13),
                (assign, "$g_gore_on", 1),
                (assign, "$g_charge_on", 1),
                (assign, "$use_player_auxiliary", 1),
                (assign, "$g_autoloot_active", 1),
                (assign, "$g_realistic_wounding", 1),
                (assign, "$vc_wounds_on", 0),
                (assign, "$moralep_on", 1),
                (assign, "$g_body_guard_on", 1),
                (assign, "$g_schield_bash", 0),
                (assign, "$g_governor_appointment_message", 1),
                (assign, "$show_truce_expired", 0),
                (assign, "$show_raid_messages", 0),
                (assign, "$g_love_messages_on", 1),
                (assign, "$g_show_senate_meeting", 1),
                (assign, "$g_report_enemies", 0),
                (assign, "$g_display_gift", 0),
                (options_set_damage_to_player, 1),
                (options_set_damage_to_friends, 1),
                (options_set_combat_ai, 1),
                (options_set_campaign_ai, 1),
                (options_set_combat_speed, 2),
            (else_try),
                (eq, ":var_1", 3),
                (assign, "$difficulty_type", 12),
                (assign, "$g_gore_on", 0),
                (assign, "$g_charge_on", 0),
                (assign, "$use_player_auxiliary", 1),
                (assign, "$g_autoloot_active", 1),
                (assign, "$g_realistic_wounding", 0),
                (assign, "$vc_wounds_on", 0),
                (assign, "$moralep_on", 0),
                (assign, "$g_body_guard_on", 1),
                (assign, "$g_schield_bash", 0),
                (assign, "$g_governor_appointment_message", 1),
                (assign, "$show_truce_expired", 0),
                (assign, "$show_raid_messages", 0),
                (assign, "$g_love_messages_on", 1),
                (assign, "$g_show_senate_meeting", 1),
                (assign, "$g_report_enemies", 0),
                (assign, "$g_display_gift", 0),
                (options_set_damage_to_player, 0),
                (options_set_damage_to_friends, 0),
                (options_set_combat_ai, 2),
                (options_set_campaign_ai, 2),
                (options_set_combat_speed, 0),
            (else_try),
                (eq, ":var_1", 4),
                (assign, "$difficulty_type", 11),
            (try_end),
            (options_get_damage_to_player, reg8),
            (overlay_set_val, "$g_presentation_obj_25", reg8),
            (options_get_damage_to_friends, reg8),
            (overlay_set_val, "$g_presentation_obj_26", reg8),
            (options_get_combat_ai, reg8),
            (overlay_set_val, "$g_presentation_obj_27", reg8),
            (options_get_combat_speed, reg8),
            (overlay_set_val, "$g_presentation_obj_29", reg8),
            (options_get_campaign_ai, reg8),
            (overlay_set_val, "$g_presentation_obj_28", reg8),
            (overlay_set_val, "$g_presentation_obj_14", "$g_charge_on"),
            (overlay_set_val, "$g_presentation_obj_15", "$use_player_auxiliary"),
            (overlay_set_val, "$g_presentation_obj_20", "$g_autoloot_active"),
            (overlay_set_val, "$g_presentation_obj_31", "$g_realistic_wounding"),
            (overlay_set_val, "$g_presentation_obj_32", "$show_truce_expired"),
            (overlay_set_val, "$form_options_overlay_2", "$show_raid_messages"),
            (overlay_set_val, "$g_presentation_obj_16", "$moralep_on"),
            (overlay_set_val, "$g_presentation_obj_33", "$vc_wounds_on"),
            (overlay_set_val, "$g_presentation_obj_17", "$insanedamage_on"),
            (overlay_set_val, "$g_presentation_obj_18", "$g_gore_on"),
            (overlay_set_val, "$g_presentation_obj_admin_panel_2", "$g_schield_bash"),
            (overlay_set_val, "$g_presentation_obj_24", "$g_display_gift"),
            (overlay_set_val, "$g_presentation_obj_admin_panel_4", "$g_report_enemies"),
            (overlay_set_val, "$g_presentation_obj_9", "$g_show_senate_meeting"),
            (overlay_set_val, "$g_presentation_obj_admin_panel_7", "$g_governor_appointment_message"),
            (overlay_set_val, "$form_options_overlay_2", "$show_raid_messages"),
            (overlay_set_val, "$g_presentation_obj_11", "$g_love_messages_on"),
            (overlay_set_val, "$g_presentation_obj_admin_panel_8", "$g_body_guard_on"),
        (else_try),
            (assign, "$difficulty_type", 11),
            (overlay_set_val, "$g_presentation_obj_6", 4),
            (overlay_set_val, ":var_0", ":var_1"),
            (eq, ":var_0", "$g_presentation_obj_11"),
            (assign, "$g_love_messages_on", ":var_1"),
        (else_try),
            (eq, ":var_0", "$g_presentation_obj_14"),
            (assign, "$g_charge_on", ":var_1"),
        (else_try),
            (eq, ":var_0", "$g_presentation_obj_15"),
            (assign, "$use_player_auxiliary", ":var_1"),
        (else_try),
            (eq, ":var_0", "$g_presentation_obj_16"),
            (assign, "$moralep_on", ":var_1"),
        (else_try),
            (eq, ":var_0", "$g_presentation_obj_17"),
            (assign, "$insanedamage_on", ":var_1"),
        (else_try),
            (eq, ":var_0", "$g_presentation_obj_18"),
            (assign, "$g_gore_on", ":var_1"),
        (else_try),
            (eq, ":var_0", "$g_presentation_obj_20"),
            (assign, "$g_autoloot_active", ":var_1"),
        (else_try),
            (eq, ":var_0", "$g_presentation_obj_21"),
            (assign, "$form_ai_off", ":var_1"),
        (else_try),
            (eq, ":var_0", "$g_presentation_obj_22"),
            (assign, "$form_ai_autorotate", ":var_1"),
        (else_try),
            (eq, ":var_0", "$g_presentation_obj_24"),
            (assign, "$g_display_gift", ":var_1"),
        (else_try),
            (eq, ":var_0", "$g_presentation_obj_25"),
            (options_set_damage_to_player, ":var_1"),
        (else_try),
            (eq, ":var_0", "$g_presentation_obj_26"),
            (options_set_damage_to_friends, ":var_1"),
        (else_try),
            (eq, ":var_0", "$g_presentation_obj_27"),
            (options_set_combat_ai, ":var_1"),
        (else_try),
            (eq, ":var_0", "$g_presentation_obj_28"),
            (options_set_campaign_ai, ":var_1"),
            (call_script, "update_party_creation_random_limits"),
        (else_try),
            (eq, ":var_0", "$g_presentation_obj_29"),
            (options_set_combat_speed, ":var_1"),
        (else_try),
            (eq, ":var_0", "$g_presentation_obj_33"),
            (assign, "$vc_wounds_on", ":var_1"),
        (else_try),
            (eq, ":var_0", "$g_presentation_obj_30"),
            (options_set_battle_size, ":var_1"),
            (str_store_string, s2, "str_battle_size"),
            (str_store_string, s3, "str_performance_feature"),
            (call_script, "current_battle_size"),
            (str_store_string, s2, "@{s2} {reg0}"),
            (str_store_string, s4, "str_battle_size_text"),
            (str_store_string, s3, "@{s3}^^{s4}"),
            (overlay_set_text, "$g_presentation_obj_3", s2),
            (overlay_set_text, "$g_presentation_obj_7", s3),
            (try_begin),
                (gt, reg0, 300),
                (overlay_set_color, "$g_presentation_obj_3", 16711680),
            (try_end),
        (else_try),
            (eq, ":var_0", "$g_presentation_obj_31"),
            (assign, "$g_realistic_wounding", ":var_1"),
        (else_try),
            (eq, ":var_0", "$g_presentation_obj_32"),
            (assign, "$show_truce_expired", ":var_1"),
        (else_try),
            (eq, ":var_0", "$form_options_overlay_1"),
            (assign, "$form_ai_player_in_division", ":var_1"),
        (else_try),
            (eq, ":var_0", "$form_options_overlay_2"),
            (assign, "$show_raid_messages", ":var_1"),
        (else_try),
            (eq, ":var_0", "$g_presentation_obj_9"),
            (assign, "$g_show_senate_meeting", ":var_1"),
        (else_try),
            (eq, ":var_0", "$g_presentation_obj_admin_panel_8"),
            (assign, "$g_body_guard_on", ":var_1"),
        (else_try),
            (eq, ":var_0", "$g_presentation_obj_admin_panel_7"),
            (assign, "$g_governor_appointment_message", ":var_1"),
        (else_try),
            (eq, ":var_0", "$g_presentation_obj_admin_panel_4"),
            (assign, "$g_report_enemies", ":var_1"),
        (else_try),
            (eq, ":var_0", "$g_presentation_obj_admin_panel_2"),
            (assign, "$g_schield_bash", ":var_1"),
        (else_try),
            (eq, ":var_0", "$g_presentation_obj_admin_panel_6"),
            (try_begin),
                (eq, ":var_1", 2),
                (assign, "$g_province_names", 0),
            (else_try),
                (eq, ":var_1", 1),
                (assign, "$g_province_names", 1),
            (else_try),
                (assign, "$g_province_names", 2),
            (try_end),
        (else_try),
            (eq, ":var_0", "$g_presentation_obj_admin_panel_9"),
            (assign, "$g_campaign_type", ":var_1"),
        (try_end),
    ]),
    (ti_on_presentation_run, [
        (try_begin),
            (key_clicked, key_xbox_b),
            (presentation_set_duration, 0),
            (try_begin),
                (eq, "$moralep_on", 0),
                (party_set_slot, "p_main_party", 195, 0),
            (try_end),
            (call_script, "dplmc_update_info_settings"),
            (try_begin),
                (eq, reg60, 0),
                (jump_to_menu, "mnu_camp"),
            (else_try),
                (try_begin),
                    (this_or_next|eq, "$g_campaign_type", 0),
                    (this_or_next|eq, "$g_campaign_type", 2),
                    (eq, "$g_campaign_type", 1),
                    (jump_to_menu, "mnu_start_game_sandbox"),
                (else_try),
                    (jump_to_menu, "mnu_start_game_1"),
                (try_end),
            (try_end),
        (else_try),
            (key_clicked, key_xbox_x),
            (presentation_set_duration, 0),
            (call_script, "dplmc_update_info_settings"),
            (try_begin),
                (eq, reg60, 0),
                (jump_to_menu, "mnu_camp"),
            (else_try),
                (jump_to_menu, "mnu_start_game_11"),
            (try_end),
        (try_end),
    ]),
]),

("95", 0, "mesh_load_window", [
    (ti_on_presentation_load, [
        (presentation_set_duration, 999999),
        (set_fixed_point_multiplier, 1000),
        (try_for_range, ":var_0", 1, 30),
            (troop_set_slot, "trp_temp_array_a", ":var_0", -1),
            (troop_set_slot, "trp_temp_array_b", ":var_0", -1),
        (try_end),
        (assign, ":var_1", 0),
        (try_for_range, ":var_2", "fac_kingdom_1", "fac_kingdoms_end"),
            (store_sub, ":var_0", ":var_2", "fac_kingdom_1"),
            (troop_set_slot, "trp_temp_array_b", ":var_0", -1),
            (assign, ":var_3", 0),
            (try_begin),
                (troop_slot_eq, "trp_global_variables", 72, 63),
                (is_between, ":var_2", 49, 53),
                (assign, ":var_3", 1),
            (try_end),
            (eq, ":var_3", 0),
            (val_add, ":var_0", 1),
            (troop_set_slot, "trp_temp_array_a", ":var_0", ":var_2"),
            (val_add, ":var_1", 1),
        (try_end),
        (create_combo_button_overlay, "$g_presentation_obj_1"),
        (position_set_x, pos1, 750),
        (position_set_y, pos1, 710),
        (overlay_set_position, "$g_presentation_obj_1", pos1),
        (overlay_add_item, "$g_presentation_obj_1", "@Year 63 AD (Nero's terror)"),
        (overlay_add_item, "$g_presentation_obj_1", "@Year 68 AD (Four Caesars)"),
        (try_begin),
            (troop_slot_eq, "trp_global_variables", 72, 63),
            (overlay_set_val, "$g_presentation_obj_1", 0),
        (else_try),
            (overlay_set_val, "$g_presentation_obj_1", 1),
        (try_end),
        (try_begin),
            (gt, "$temp_troop", -1),
            (try_begin),
                (eq, "$temp_troop", "trp_senator_5"),
                (assign, ":var_4", "fac_kingdom_24"),
            (else_try),
                (eq, "$temp_troop", "trp_legatus_11"),
                (assign, ":var_4", "fac_kingdom_25"),
            (else_try),
                (eq, "$temp_troop", "trp_senator_2"),
                (assign, ":var_4", "fac_kingdom_26"),
            (else_try),
                (eq, "$temp_troop", "trp_senator_1"),
                (assign, ":var_4", "fac_kingdom_27"),
            (else_try),
                (store_troop_faction, ":var_4", "$temp_troop"),
            (try_end),
            (str_store_troop_name, s0, "$temp_troop"),
            (create_text_overlay, reg1, "@Selected: {s0}", 0),
            (position_set_x, pos1, 25),
            (position_set_y, pos1, 715),
            (overlay_set_position, reg1, pos1),
            (position_set_x, pos1, 950),
            (position_set_y, pos1, 950),
            (overlay_set_size, reg1, pos1),
            (create_mesh_overlay_with_tableau_material, reg0, -1, "tableau_kingdom_selection_mesh", "$temp_troop"),
            (position_set_x, pos1, 10),
            (position_set_y, pos1, 540),
            (overlay_set_position, reg0, pos1),
            (position_set_x, pos1, 500),
            (position_set_y, pos1, 500),
            (overlay_set_size, reg0, pos1),
            (try_begin),
                (eq, "$g_campaign_type", 0),
                (val_sub, ":var_4", "fac_player_supporters_faction"),
                (store_add, ":var_5", ":var_4", "str_kingdom_1_description"),
                (val_sub, ":var_5", 1),
                (str_store_string, s0, ":var_5"),
            (else_try),
                (faction_get_slot, ":var_6", ":var_4", 9),
                (store_sub, ":var_5", ":var_6", "fac_culture_dacian"),
                (val_add, ":var_5", "str_culture_dacian"),
                (str_store_string, s0, ":var_5"),
                (str_store_faction_name, s2, ":var_4"),
                (str_store_faction_name, s1, ":var_6"),
                (str_store_string, s0, "@Your faction {s2} is of {s1} culture.^^{s0}"),
            (try_end),
            (create_text_overlay, reg1, 0, 131072),
            (position_set_x, pos1, 535),
            (position_set_y, pos1, 50),
            (overlay_set_position, reg1, pos1),
            (position_set_x, pos1, 415),
            (position_set_y, pos1, 650),
            (overlay_set_area_size, reg1, pos1),
            (set_container_overlay, reg1),
            (set_container_overlay, -1),
            (try_begin),
                (eq, "$g_campaign_type", 0),
                (create_text_overlay, reg1, "@Character information", 65536),
                (overlay_set_color, reg1, 10255360),
                (position_set_x, pos1, 1000),
                (position_set_y, pos1, 1000),
                (overlay_set_size, reg1, pos1),
                (position_set_x, pos1, 295),
                (position_set_y, pos1, 710),
                (overlay_set_position, reg1, pos1),
                (str_clear, s0),
                (create_text_overlay, reg1, 0, 131072),
                (position_set_x, pos1, 225),
                (position_set_y, pos1, 550),
                (overlay_set_position, reg1, pos1),
                (position_set_x, pos1, 260),
                (position_set_y, pos1, 150),
                (overlay_set_area_size, reg1, pos1),
                (set_container_overlay, reg1),
                (assign, ":var_7", 0),
                (try_for_range, ":var_8", "trp_npc1", "trp_heroes_end"),
                    (call_script, "troop_get_family_relation_to_troop", ":var_8", "$temp_troop"),
                    (gt, reg0, 0),
                    (val_add, ":var_7", 1),
                (try_end),
                (val_add, ":var_7", 1),
                (store_mul, ":var_9", ":var_7", 27),
                (try_for_range, ":var_8", "trp_npc1", "trp_heroes_end"),
                    (call_script, "troop_get_family_relation_to_troop", ":var_8", "$temp_troop"),
                    (gt, reg0, 0),
                    (str_store_troop_name, s1, ":var_8"),
                    (create_text_overlay, reg1, "@{s1} ({s11})", 0),
                    (position_set_x, pos1, 900),
                    (position_set_y, pos1, 900),
                    (overlay_set_size, reg1, pos1),
                    (position_set_x, pos1, 25),
                    (position_set_y, pos1, ":var_9"),
                    (overlay_set_position, reg1, pos1),
                    (val_sub, ":var_9", 27),
                (try_end),
                (troop_get_slot, reg1, "$temp_troop", 18),
                (create_text_overlay, reg1, "@Age: {reg1}", 0),
                (position_set_x, pos1, 900),
                (position_set_y, pos1, 900),
                (overlay_set_size, reg1, pos1),
                (position_set_x, pos1, 25),
                (position_set_y, pos1, ":var_9"),
                (overlay_set_position, reg1, pos1),
                (val_sub, ":var_9", 27),
                (set_container_overlay, -1),
            (try_end),
        (try_end),
        (create_game_button_overlay, reg1, "@Return"),
        (position_set_x, pos1, 300),
        (position_set_y, pos1, 10),
        (overlay_set_position, reg1, pos1),
        (assign, "$g_jrider_faction_report_return_to_menu", reg1),
        (create_game_button_overlay, reg1, "@Continue"),
        (position_set_x, pos1, 700),
        (position_set_y, pos1, 10),
        (overlay_set_position, reg1, pos1),
        (assign, "$g_jrider_faction_filter", reg1),
        (create_text_overlay, reg1, "@Rulers:", 4),
        (position_set_x, pos1, 25),
        (position_set_y, pos1, 510),
        (overlay_set_position, reg1, pos1),
        (overlay_set_color, reg1, 127),
        (position_set_x, pos1, 900),
        (position_set_y, pos1, 900),
        (overlay_set_size, reg1, pos1),
        (str_clear, s0),
        (create_text_overlay, reg1, 0, 131072),
        (position_set_x, pos1, 50),
        (position_set_y, pos1, 50),
        (overlay_set_position, reg1, pos1),
        (position_set_x, pos1, 450),
        (position_set_y, pos1, 450),
        (overlay_set_area_size, reg1, pos1),
        (store_div, ":var_10", ":var_1", 2),
        (val_mul, ":var_10", 225),
        (assign, ":var_11", 20),
        (position_set_x, pos2, 900),
        (position_set_y, pos2, 900),
        (set_container_overlay, reg1),
        (try_for_range, ":var_0", 1, 30),
            (troop_get_slot, ":var_12", "trp_temp_array_a", ":var_0"),
            (gt, ":var_12", -1),
            (try_begin),
                (eq, ":var_12", "fac_kingdom_24"),
                (assign, ":var_13", "trp_senator_5"),
            (else_try),
                (eq, ":var_12", "fac_kingdom_25"),
                (assign, ":var_13", "trp_legatus_11"),
            (else_try),
                (eq, ":var_12", "fac_kingdom_26"),
                (assign, ":var_13", "trp_senator_2"),
            (else_try),
                (eq, ":var_12", "fac_kingdom_27"),
                (assign, ":var_13", "trp_senator_1"),
            (else_try),
                (faction_get_slot, ":var_13", ":var_12", 10),
            (try_end),
            (is_between, ":var_13", "trp_kingdom_1_lord", "trp_heroes_end"),
            (neq, "$temp_troop", ":var_13"),
            (try_begin),
                (ge, ":var_11", 460),
                (assign, ":var_11", 0),
                (val_sub, ":var_10", 220),
            (try_end),
            (assign, reg0, 0),
            (try_begin),
                (troop_slot_eq, "trp_global_variables", 72, 68),
                (eq, ":var_12", "fac_kingdom_7"),
                (assign, reg0, 1),
            (try_end),
            (eq, reg0, 0),
            (create_mesh_overlay_with_tableau_material, reg0, -1, "tableau_kingdom_selection_mesh", ":var_13"),
            (position_set_x, pos1, ":var_11"),
            (position_set_y, pos1, ":var_10"),
            (overlay_set_position, reg0, pos1),
            (position_set_x, pos3, 500),
            (position_set_y, pos3, 500),
            (overlay_set_size, reg0, pos3),
            (create_image_button_overlay, reg10, "mesh_longer_button", "mesh_longer_button"),
            (overlay_set_position, reg10, pos1),
            (position_set_x, pos3, 1000),
            (position_set_y, pos3, 2000),
            (overlay_set_size, reg10, pos3),
            (overlay_set_alpha, reg10, 0),
            (overlay_set_color, reg10, 14540253),
            (troop_set_slot, "trp_temp_array_b", ":var_0", reg10),
            (str_store_troop_name, s0, ":var_13"),
            (create_text_overlay, reg1, "str_s0", 4),
            (position_set_x, pos1, ":var_11"),
            (store_sub, ":var_14", ":var_10", 20),
            (position_set_y, pos1, ":var_14"),
            (overlay_set_position, reg1, pos1),
            (overlay_set_size, reg1, pos2),
            (str_store_faction_name, s21, ":var_12"),
            (create_text_overlay, reg1, "@{s21}", 4),
            (position_set_x, pos1, ":var_11"),
            (store_sub, ":var_14", ":var_10", 40),
            (position_set_y, pos1, ":var_14"),
            (overlay_set_position, reg1, pos1),
            (overlay_set_size, reg1, pos2),
            (val_add, ":var_11", 230),
        (try_end),
        (set_container_overlay, -1),
    ]),
    (ti_on_presentation_event_state_change, [
        (store_trigger_param_1, ":var_0"),
        (store_trigger_param_2, ":var_1"),
        (try_begin),
            (eq, ":var_0", "$g_presentation_obj_1"),
            (assign, "$g_presentation_obj_1", ":var_1"),
            (try_begin),
                (eq, ":var_1", 0),
                (troop_set_slot, "trp_global_variables", 72, 63),
            (else_try),
                (troop_set_slot, "trp_global_variables", 72, 68),
            (try_end),
            (start_presentation, "prsnt_95"),
        (else_try),
            (eq, ":var_0", "$g_jrider_faction_report_return_to_menu"),
            (jump_to_menu, "mnu_start_game_0"),
            (presentation_set_duration, 0),
        (else_try),
            (assign, ":var_2", 30),
            (try_for_range, ":var_3", 1, ":var_2"),
                (troop_slot_eq, "trp_temp_array_b", ":var_3", ":var_0"),
                (troop_get_slot, ":var_4", "trp_temp_array_a", ":var_3"),
                (assign, ":var_2", -1),
            (try_end),
            (eq, ":var_2", -1),
            (try_begin),
                (eq, ":var_4", "fac_kingdom_24"),
                (assign, "$temp_troop", "trp_senator_5"),
            (else_try),
                (eq, ":var_4", "fac_kingdom_25"),
                (assign, "$temp_troop", "trp_legatus_11"),
            (else_try),
                (eq, ":var_4", "fac_kingdom_26"),
                (assign, "$temp_troop", "trp_senator_2"),
            (else_try),
                (eq, ":var_4", "fac_kingdom_27"),
                (assign, "$temp_troop", "trp_senator_1"),
            (else_try),
                (faction_get_slot, "$temp_troop", ":var_4", 10),
            (try_end),
            (start_presentation, "prsnt_95"),
        (else_try),
            (eq, ":var_0", "$g_jrider_faction_filter"),
            (try_begin),
                (is_between, "$temp_troop", "trp_kingdom_1_lord", "trp_heroes_end"),
                (try_begin),
                    (eq, "$temp_troop", "trp_senator_5"),
                    (assign, ":var_4", "fac_kingdom_24"),
                (else_try),
                    (eq, "$temp_troop", "trp_legatus_11"),
                    (assign, ":var_4", "fac_kingdom_25"),
                (else_try),
                    (eq, "$temp_troop", "trp_senator_2"),
                    (assign, ":var_4", "fac_kingdom_26"),
                (else_try),
                    (eq, "$temp_troop", "trp_senator_1"),
                    (assign, ":var_4", "fac_kingdom_27"),
                (else_try),
                    (store_troop_faction, ":var_4", "$temp_troop"),
                (try_end),
                (try_begin),
                    (eq, "$g_campaign_type", 0),
                    (call_script, "player_is_king", ":var_4"),
                (else_try),
                    (call_script, "player_is_lord", ":var_4"),
                (try_end),
                (presentation_set_duration, 0),
                (jump_to_menu, "mnu_choose_skill"),
            (else_try),
                (display_message, "@Select a king!", 10255360),
            (try_end),
        (try_end),
    ]),
    (ti_on_presentation_run, [
        (try_begin),
            (key_clicked, key_space),
            (set_fixed_point_multiplier, 1000),
            (mouse_get_position, pos31),
            (position_get_x, reg31, pos31),
            (position_get_y, reg32, pos31),
            (display_message, "@X: {reg31} | Y: {reg32}"),
        (try_end),
    ]),
]),

("96", 0, 0, [
    (ti_on_presentation_load, [
        (presentation_set_duration, 999999),
        (set_fixed_point_multiplier, 1000),
        (create_mesh_overlay, reg1, "mesh_load_window"),
        (position_set_x, pos1, 0),
        (position_set_y, pos1, 0),
        (overlay_set_position, reg1, pos1),
        (create_combo_button_overlay, "$g_presentation_obj_6"),
        (position_set_x, pos1, 750),
        (position_set_y, pos1, 710),
        (overlay_set_position, "$g_presentation_obj_6", pos1),
        (overlay_add_item, "$g_presentation_obj_6", "@Year 63 AD (Nero's terror)"),
        (overlay_add_item, "$g_presentation_obj_6", "@Year 68 AD (Four Caesars)"),
        (try_begin),
            (troop_slot_eq, "trp_global_variables", 72, 63),
            (overlay_set_val, "$g_presentation_obj_6", 0),
        (else_try),
            (overlay_set_val, "$g_presentation_obj_6", 1),
        (try_end),
        (create_game_button_overlay, "$g_presentation_obj_1", "@Done"),
        (position_set_x, pos1, 875),
        (position_set_y, pos1, 35),
        (overlay_set_position, "$g_presentation_obj_1", pos1),
        (create_game_button_overlay, "$g_presentation_obj_2", "@Back"),
        (position_set_x, pos1, 700),
        (position_set_y, pos1, 35),
        (overlay_set_position, "$g_presentation_obj_2", pos1),
        (create_game_button_overlay, "$g_presentation_obj_3", "@Default"),
        (position_set_x, pos1, 125),
        (position_set_y, pos1, 35),
        (overlay_set_position, "$g_presentation_obj_3", pos1),
        (create_text_overlay, reg1, "@Character Creation", 16),
        (position_set_x, pos1, 1500),
        (position_set_y, pos1, 1500),
        (overlay_set_size, reg1, pos1),
        (position_set_x, pos1, 500),
        (position_set_y, pos1, 690),
        (overlay_set_position, reg1, pos1),
        (assign, ":var_0", 695),
        (create_text_overlay, reg1, "@Background:", 16),
        (position_set_x, pos1, 1200),
        (position_set_y, pos1, 1200),
        (overlay_set_size, reg1, pos1),
        (position_set_x, pos1, 150),
        (position_set_y, pos1, ":var_0"),
        (overlay_set_position, reg1, pos1),
        (val_sub, ":var_0", 40),
        (create_text_overlay, reg1, "@Culture:", 16),
        (position_set_x, pos1, 1000),
        (position_set_y, pos1, 1000),
        (overlay_set_size, reg1, pos1),
        (position_set_x, pos1, 150),
        (position_set_y, pos1, ":var_0"),
        (overlay_set_position, reg1, pos1),
        (val_sub, ":var_0", 30),
        (create_combo_button_overlay, "$g_presentation_obj_region"),
        (position_set_x, pos1, 175),
        (position_set_y, pos1, ":var_0"),
        (overlay_set_position, "$g_presentation_obj_region", pos1),
        (position_set_x, pos1, 800),
        (position_set_y, pos1, 800),
        (overlay_set_size, "$g_presentation_obj_region", pos1),
        (try_for_range, ":var_1", "fac_culture_dacian", "fac_player_faction"),
            (str_store_faction_name, s1, ":var_1"),
            (overlay_add_item, "$g_presentation_obj_region", "@{s1}"),
        (try_end),
        (store_sub, ":var_2", "$background_answer_4", "fac_culture_dacian"),
        (overlay_set_val, "$g_presentation_obj_region", ":var_2"),
        (val_sub, ":var_0", 40),
        (create_text_overlay, reg1, "@Gender:", 16),
        (position_set_x, pos1, 1000),
        (position_set_y, pos1, 1000),
        (overlay_set_size, reg1, pos1),
        (position_set_x, pos1, 150),
        (position_set_y, pos1, ":var_0"),
        (overlay_set_position, reg1, pos1),
        (val_sub, ":var_0", 30),
        (create_combo_button_overlay, "$g_presentation_obj_gender", 16),
        (position_set_x, pos1, 175),
        (position_set_y, pos1, ":var_0"),
        (overlay_set_position, "$g_presentation_obj_gender", pos1),
        (position_set_x, pos1, 800),
        (position_set_y, pos1, 800),
        (overlay_set_size, "$g_presentation_obj_gender", pos1),
        (overlay_add_item, "$g_presentation_obj_gender", "@Man"),
        (overlay_add_item, "$g_presentation_obj_gender", "@Woman"),
        (overlay_set_val, "$g_presentation_obj_gender", "$character_gender"),
        (val_sub, ":var_0", 40),
        (create_text_overlay, reg1, "@Status:", 16),
        (position_set_x, pos1, 1000),
        (position_set_y, pos1, 1000),
        (overlay_set_size, reg1, pos1),
        (position_set_x, pos1, 150),
        (position_set_y, pos1, ":var_0"),
        (overlay_set_position, reg1, pos1),
        (val_sub, ":var_0", 30),
        (create_combo_button_overlay, "$g_presentation_obj_father"),
        (position_set_x, pos1, 175),
        (position_set_y, pos1, ":var_0"),
        (overlay_set_position, "$g_presentation_obj_father", pos1),
        (position_set_x, pos1, 800),
        (position_set_y, pos1, 800),
        (overlay_set_size, "$g_presentation_obj_father", pos1),
        (overlay_add_item, "$g_presentation_obj_father", "@Slave"),
        (overlay_add_item, "$g_presentation_obj_father", "@Freeman"),
        (overlay_add_item, "$g_presentation_obj_father", "@Lesser Noble"),
        (overlay_set_val, "$g_presentation_obj_father", "$background_type"),
        (val_sub, ":var_0", 40),
        (create_text_overlay, reg1, "@Body Build:", 16),
        (position_set_x, pos1, 1000),
        (position_set_y, pos1, 1000),
        (overlay_set_size, reg1, pos1),
        (position_set_x, pos1, 150),
        (position_set_y, pos1, ":var_0"),
        (overlay_set_position, reg1, pos1),
        (val_sub, ":var_0", 30),
        (create_combo_button_overlay, "$g_presentation_obj_early"),
        (position_set_x, pos1, 175),
        (position_set_y, pos1, ":var_0"),
        (overlay_set_position, "$g_presentation_obj_early", pos1),
        (position_set_x, pos1, 800),
        (position_set_y, pos1, 800),
        (overlay_set_size, "$g_presentation_obj_early", pos1),
        (overlay_add_item, "$g_presentation_obj_early", "@Strong"),
        (overlay_add_item, "$g_presentation_obj_early", "@Agile"),
        (overlay_add_item, "$g_presentation_obj_early", "@Weak"),
        (overlay_set_val, "$g_presentation_obj_early", "$background_answer_2"),
        (val_sub, ":var_0", 40),
        (create_text_overlay, reg1, "@Mind:", 16),
        (position_set_x, pos1, 1000),
        (position_set_y, pos1, 1000),
        (overlay_set_size, reg1, pos1),
        (position_set_x, pos1, 150),
        (position_set_y, pos1, ":var_0"),
        (overlay_set_position, reg1, pos1),
        (val_sub, ":var_0", 30),
        (create_combo_button_overlay, "$g_presentation_obj_adult"),
        (position_set_x, pos1, 175),
        (position_set_y, pos1, ":var_0"),
        (overlay_set_position, "$g_presentation_obj_adult", pos1),
        (position_set_x, pos1, 800),
        (position_set_y, pos1, 800),
        (overlay_set_size, "$g_presentation_obj_adult", pos1),
        (overlay_add_item, "$g_presentation_obj_adult", "@Genius"),
        (overlay_add_item, "$g_presentation_obj_adult", "@Shrewd"),
        (overlay_add_item, "$g_presentation_obj_adult", "@Normal"),
        (overlay_add_item, "$g_presentation_obj_adult", "@Dull"),
        (overlay_set_val, "$g_presentation_obj_adult", "$background_answer_3"),
        (val_sub, ":var_0", 40),
        (create_text_overlay, reg1, "@Biography:", 16),
        (position_set_x, pos1, 1200),
        (position_set_y, pos1, 1200),
        (overlay_set_size, reg1, pos1),
        (position_set_x, pos1, 500),
        (position_set_y, pos1, 660),
        (overlay_set_position, reg1, pos1),
        (call_script, "mcc_get_character_background_text"),
        (create_text_overlay, "$g_presentation_obj_story", "@{s1}", 10240),
        (position_set_x, pos1, 320),
        (position_set_y, pos1, 90),
        (overlay_set_position, "$g_presentation_obj_story", pos1),
        (position_set_x, pos1, 340),
        (position_set_y, pos1, 520),
        (overlay_set_area_size, "$g_presentation_obj_story", pos1),
        (create_text_overlay, reg1, "@Stat Changes:", 16),
        (position_set_x, pos1, 1200),
        (position_set_y, pos1, 1200),
        (overlay_set_size, reg1, pos1),
        (position_set_x, pos1, 835),
        (position_set_y, pos1, 660),
        (overlay_set_position, reg1, pos1),
        (str_clear, s5),
        (create_text_overlay, reg1, "@Str", 16),
        (position_set_x, pos1, 900),
        (position_set_y, pos1, 900),
        (overlay_set_size, reg1, pos1),
        (position_set_x, pos1, 760),
        (position_set_y, pos1, 620),
        (overlay_set_position, reg1, pos1),
        (create_text_overlay, "$g_presentation_obj_strength", "str_mcc_zero", 16),
        (position_set_x, pos1, 850),
        (position_set_y, pos1, 850),
        (overlay_set_size, "$g_presentation_obj_strength", pos1),
        (position_set_x, pos1, 760),
        (position_set_y, pos1, 595),
        (overlay_set_position, "$g_presentation_obj_strength", pos1),
        (create_text_overlay, reg1, "@Agi", 16),
        (position_set_x, pos1, 900),
        (position_set_y, pos1, 900),
        (overlay_set_size, reg1, pos1),
        (position_set_x, pos1, 805),
        (position_set_y, pos1, 620),
        (overlay_set_position, reg1, pos1),
        (create_text_overlay, "$g_presentation_obj_agility", "str_mcc_zero", 16),
        (position_set_x, pos1, 850),
        (position_set_y, pos1, 850),
        (overlay_set_size, "$g_presentation_obj_agility", pos1),
        (position_set_x, pos1, 805),
        (position_set_y, pos1, 595),
        (overlay_set_position, "$g_presentation_obj_agility", pos1),
        (create_text_overlay, reg1, "@Int", 16),
        (position_set_x, pos1, 900),
        (position_set_y, pos1, 900),
        (overlay_set_size, reg1, pos1),
        (position_set_x, pos1, 850),
        (position_set_y, pos1, 620),
        (overlay_set_position, reg1, pos1),
        (create_text_overlay, "$g_presentation_obj_intel", "str_mcc_zero", 16),
        (position_set_x, pos1, 850),
        (position_set_y, pos1, 850),
        (overlay_set_size, "$g_presentation_obj_intel", pos1),
        (position_set_x, pos1, 850),
        (position_set_y, pos1, 595),
        (overlay_set_position, "$g_presentation_obj_intel", pos1),
        (create_text_overlay, reg1, "@Cha", 16),
        (position_set_x, pos1, 900),
        (position_set_y, pos1, 900),
        (overlay_set_size, reg1, pos1),
        (position_set_x, pos1, 895),
        (position_set_y, pos1, 620),
        (overlay_set_position, reg1, pos1),
        (create_text_overlay, "$g_presentation_obj_charisma", "str_mcc_zero", 16),
        (position_set_x, pos1, 850),
        (position_set_y, pos1, 850),
        (overlay_set_size, "$g_presentation_obj_charisma", pos1),
        (position_set_x, pos1, 895),
        (position_set_y, pos1, 595),
        (overlay_set_position, "$g_presentation_obj_charisma", pos1),
        (create_text_overlay, reg1, "@Gold"),
        (position_set_x, pos1, 900),
        (position_set_y, pos1, 900),
        (overlay_set_size, reg1, pos1),
        (position_set_x, pos1, 695),
        (position_set_y, pos1, 520),
        (overlay_set_position, reg1, pos1),
        (create_text_overlay, "$g_presentation_obj_gold", "str_mcc_zero", 16),
        (position_set_x, pos1, 850),
        (position_set_y, pos1, 850),
        (overlay_set_size, "$g_presentation_obj_gold", pos1),
        (position_set_x, pos1, 805),
        (position_set_y, pos1, 520),
        (overlay_set_position, "$g_presentation_obj_gold", pos1),
        (create_text_overlay, reg1, "@Renown"),
        (position_set_x, pos1, 900),
        (position_set_y, pos1, 900),
        (overlay_set_size, reg1, pos1),
        (position_set_x, pos1, 695),
        (position_set_y, pos1, 500),
        (overlay_set_position, reg1, pos1),
        (create_text_overlay, "$g_presentation_obj_renown", "str_mcc_zero", 16),
        (position_set_x, pos1, 850),
        (position_set_y, pos1, 850),
        (overlay_set_size, "$g_presentation_obj_renown", pos1),
        (position_set_x, pos1, 805),
        (position_set_y, pos1, 500),
        (overlay_set_position, "$g_presentation_obj_renown", pos1),
        (create_text_overlay, reg1, "@One Handed"),
        (position_set_x, pos1, 900),
        (position_set_y, pos1, 900),
        (overlay_set_size, reg1, pos1),
        (position_set_x, pos1, 695),
        (position_set_y, pos1, 480),
        (overlay_set_position, reg1, pos1),
        (create_text_overlay, "$g_presentation_obj_onehand", "str_mcc_zero", 16),
        (position_set_x, pos1, 850),
        (position_set_y, pos1, 850),
        (overlay_set_size, "$g_presentation_obj_onehand", pos1),
        (position_set_x, pos1, 805),
        (position_set_y, pos1, 480),
        (overlay_set_position, "$g_presentation_obj_onehand", pos1),
        (create_text_overlay, reg1, "@Two Handed"),
        (position_set_x, pos1, 900),
        (position_set_y, pos1, 900),
        (overlay_set_size, reg1, pos1),
        (position_set_x, pos1, 695),
        (position_set_y, pos1, 460),
        (overlay_set_position, reg1, pos1),
        (create_text_overlay, "$g_presentation_obj_twohand", "str_mcc_zero", 16),
        (position_set_x, pos1, 850),
        (position_set_y, pos1, 850),
        (overlay_set_size, "$g_presentation_obj_twohand", pos1),
        (position_set_x, pos1, 805),
        (position_set_y, pos1, 460),
        (overlay_set_position, "$g_presentation_obj_twohand", pos1),
        (create_text_overlay, reg1, "@Polearms"),
        (position_set_x, pos1, 900),
        (position_set_y, pos1, 900),
        (overlay_set_size, reg1, pos1),
        (position_set_x, pos1, 695),
        (position_set_y, pos1, 440),
        (overlay_set_position, reg1, pos1),
        (create_text_overlay, "$g_presentation_obj_polearm", "str_mcc_zero", 16),
        (position_set_x, pos1, 850),
        (position_set_y, pos1, 850),
        (overlay_set_size, "$g_presentation_obj_polearm", pos1),
        (position_set_x, pos1, 805),
        (position_set_y, pos1, 440),
        (overlay_set_position, "$g_presentation_obj_polearm", pos1),
        (create_text_overlay, reg1, "@Bows"),
        (position_set_x, pos1, 900),
        (position_set_y, pos1, 900),
        (overlay_set_size, reg1, pos1),
        (position_set_x, pos1, 695),
        (position_set_y, pos1, 420),
        (overlay_set_position, reg1, pos1),
        (create_text_overlay, "$g_presentation_obj_bow", "str_mcc_zero", 16),
        (position_set_x, pos1, 850),
        (position_set_y, pos1, 850),
        (overlay_set_size, "$g_presentation_obj_bow", pos1),
        (position_set_x, pos1, 805),
        (position_set_y, pos1, 420),
        (overlay_set_position, "$g_presentation_obj_bow", pos1),
        (create_text_overlay, reg1, "@Ballista"),
        (position_set_x, pos1, 900),
        (position_set_y, pos1, 900),
        (overlay_set_size, reg1, pos1),
        (position_set_x, pos1, 695),
        (position_set_y, pos1, 400),
        (overlay_set_position, reg1, pos1),
        (create_text_overlay, "$g_presentation_obj_xbow", "str_mcc_zero", 16),
        (position_set_x, pos1, 850),
        (position_set_y, pos1, 850),
        (overlay_set_size, "$g_presentation_obj_xbow", pos1),
        (position_set_x, pos1, 805),
        (position_set_y, pos1, 400),
        (overlay_set_position, "$g_presentation_obj_xbow", pos1),
        (create_text_overlay, reg1, "@Throwing"),
        (position_set_x, pos1, 900),
        (position_set_y, pos1, 900),
        (overlay_set_size, reg1, pos1),
        (position_set_x, pos1, 695),
        (position_set_y, pos1, 380),
        (overlay_set_position, reg1, pos1),
        (create_text_overlay, "$g_presentation_obj_throw", "str_mcc_zero", 16),
        (position_set_x, pos1, 850),
        (position_set_y, pos1, 850),
        (overlay_set_size, "$g_presentation_obj_throw", pos1),
        (position_set_x, pos1, 805),
        (position_set_y, pos1, 380),
        (overlay_set_position, "$g_presentation_obj_throw", pos1),
        (call_script, "mcc_generate_skill_set", 0),
    ]),
    (ti_on_presentation_event_state_change, [
        (store_trigger_param_1, ":var_0"),
        (store_trigger_param_2, ":var_1"),
        (try_begin),
            (eq, ":var_0", "$g_presentation_obj_6"),
            (assign, "$g_presentation_obj_6", ":var_1"),
            (try_begin),
                (eq, ":var_1", 0),
                (troop_set_slot, "trp_global_variables", 72, 63),
            (else_try),
                (troop_set_slot, "trp_global_variables", 72, 68),
            (try_end),
            (start_presentation, "prsnt_96"),
        (else_try),
            (eq, ":var_0", "$g_presentation_obj_1"),
            (call_script, "mcc_end_presentation_begin_game"),
            (try_begin),
                (presentation_set_duration, 0),
                (jump_to_menu, "mnu_choose_skill"),
            (try_end),
        (else_try),
            (eq, ":var_0", "$g_presentation_obj_2"),
            (jump_to_menu, "mnu_start_game_0"),
            (presentation_set_duration, 0),
        (else_try),
            (eq, ":var_0", "$g_presentation_obj_3"),
            (call_script, "mcc_default_settings"),
            (start_presentation, "prsnt_96"),
        (else_try),
            (eq, ":var_0", "$g_presentation_obj_gender"),
            (assign, "$character_gender", ":var_1"),
            (start_presentation, "prsnt_96"),
            (assign, "$g_presentation_obj_gender", ":var_1"),
        (else_try),
            (eq, ":var_0", "$g_presentation_obj_father"),
            (assign, "$background_type", ":var_1"),
            (start_presentation, "prsnt_96"),
            (assign, "$g_presentation_obj_father", ":var_1"),
        (else_try),
            (eq, ":var_0", "$g_presentation_obj_early"),
            (assign, "$background_answer_2", ":var_1"),
            (start_presentation, "prsnt_96"),
            (assign, "$g_presentation_obj_early", ":var_1"),
        (else_try),
            (eq, ":var_0", "$g_presentation_obj_adult"),
            (assign, "$background_answer_3", ":var_1"),
            (start_presentation, "prsnt_96"),
            (assign, "$g_presentation_obj_adult", ":var_1"),
        (else_try),
            (eq, ":var_0", "$g_presentation_obj_region"),
            (assign, "$g_presentation_obj_region", ":var_1"),
            (store_add, "$background_answer_4", ":var_1", "fac_culture_dacian"),
            (start_presentation, "prsnt_96"),
        (try_end),
    ]),
]),

]
